# Generated by quail.
#
# Gherkin contract for the browse journey on https://www.spritecloud.com/.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: Spritecloud — browse journey
  As a visitor of https://www.spritecloud.com/
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "QA & Software Testing Consultancy — spriteCloud"
    When I click the link to "/work"
    Then I see the heading "Proof beats
promises."
    And the page title contains "Work — spriteCloud"
    When I click the link to "/functional-testing"
    Then I see the heading "Your launch date is set.
Your test coverage isn't."
    And the page title contains "Functional Testing — spriteCloud"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/functional-testing"
    Then I see the heading "Your launch date is set.
Your test coverage isn't."

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/functional-testing"
    When I go back in the browser history
