# Generated by quail. Declarative view of the op-list journey.
Feature: Fill and submit contact form

  @journey:composed @smoke
  Scenario: Fill and submit contact form
    Given I open "/contact"
    When I fill "Name" with "Alex Johnson"
    When I fill "Email" with "alex.johnson@example.com"
    When I fill "Company" with "Acme Innovations"
    When I fill "What are you interested in?" with "Test Automation"
    When I fill "What's the situation?" with "Seeking automation support for our web app"
    When I click the button "Send"
