# Generated by quail. Declarative view of the op-list journey.
Feature: Submit contact form

  @journey:composed @smoke
  Scenario: Submit contact form
    Given I open "/contact"
    When I fill "Name" with "Alex Johnson"
    When I fill "Email" with "alex.johnson@example.com"
    When I fill "Company" with "Acme Corp"
    When I fill "Phone" with "+1-555-123-4567"
    When I fill "What are you interested in?" with "Test Automation"
    When I fill "What's the situation?" with "We need automated functional tests for our web app."
    When I click the button "Send"
