# Generated by quail. Declarative view of the op-list journey.
Feature: Visit functional testing page and confirm heading

  @journey:coverage @smoke
  Scenario: Visit functional testing page and confirm heading
    Given I open "/functional-testing"
    Then I see the heading "Functional Testing"
