# Generated by quail. Declarative view of the op-list journey.
Feature: Visit cybersecurity page and confirm heading

  @journey:coverage @smoke
  Scenario: Visit cybersecurity page and confirm heading
    Given I open "/cybersecurity"
    Then I see the heading "Cybersecurity"
