# Generated by quail. Declarative view of the op-list journey.
Feature: Visit test automation page and verify heading

  @journey:coverage @smoke
  Scenario: Visit test automation page and verify heading
    Given I open "/test-automation"
    Then I see the main "Test Automation"
