# Generated by quail. Declarative view of the op-list journey.
Feature: Visit agentic testing page and verify heading

  @journey:coverage @smoke
  Scenario: Visit agentic testing page and verify heading
    Given I open "/agentic-testing"
    Then I see the main "Agentic Testing"
