# Generated by quail. Declarative view of the op-list journey.
Feature: Visit functional testing page and expand Company accordion

  @journey:coverage @smoke
  Scenario: Visit functional testing page and expand Company accordion
    Given I open "/functional-testing"
    When I click the menuitem "Company"
    Then I see the heading "About spriteCloud"
