# Generated by quail. Declarative view of the op-list journey.
Feature: Explore services

  @journey:composed @smoke
  Scenario: Explore services
    Given I open "/"
    When I click the link "Testing Services"
    Then I see the heading "Not a service list. A diagnostic."
    When I click the link "Functional Testing"
    Then I see the heading "Functional Testing"
