# Generated by quail. Declarative view of the op-list journey.
Feature: Explore testing services

  @journey:composed @smoke
  Scenario: Explore testing services
    Given I open "/"
    When I click the link "Testing Services"
    When I click the link "Functional Testing"
    When I click the link "Test Automation"
    When I click the link "Ready to talk?"
    When I click the link "Contact us"
