# Generated by quail.
#
# Gherkin contract for the exercise journey on https://www.spritecloud.com/test-automation.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:exercise
#   npx playwright test --grep @smoke

Feature: spriteCloud — exercise journey
  As a visitor of https://www.spritecloud.com/test-automation
  I want to complete the exercise flow
  So that the page delivers on its user goal

  @journey:exercise @priority:standard @smoke
  Scenario: exercise flow completes on the expected final page
    Given I open the landing page
    And the page title contains "Test Automation"
    And the main heading reads "Expert Test Automation Services"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:exercise @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: submitting an empty form displays validation errors
    Given I am on the landing page
    When I submit the form without filling any required field
    Then no success message is shown

Feature: Spritecloud — exercise journey
  As a visitor of https://www.spritecloud.com/test-automation
  I want to complete the exercise flow
  So that the page delivers on its user goal

  @journey:exercise @priority:standard @smoke
  Scenario: exercise journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Test Automation — spriteCloud"
    And the main heading reads "Test More.
Spend less.
Ship faster."

  @journey:exercise @priority:standard @kind:empty-state
  Scenario: exercise — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items
