# Generated by quail. Declarative view of the op-list journey.
Feature: lands on Functional Testing — spriteCloud

  @journey:composed @smoke
  Scenario: lands on Functional Testing — spriteCloud
    Given I open "https://www.spritecloud.com/functional-testing"
    Then I see the heading ""
