# Generated by quail. Declarative view of the op-list journey.
Feature: Explore spriteCloud performance testing

  @journey:composed @smoke
  Scenario: Explore spriteCloud performance testing
    Given I open "/"
    When I click the link "Performance Testing"
    Then I see the heading "That's when they leave."
    Then I see the heading "Performance is a revenue conversation."
    Then I see the heading "Where performance problems actually live."
