# Generated by quail. Declarative view of the op-list journey.
Feature: Explore spriteCloud's Performance Testing

  @journey:composed @smoke
  Scenario: Explore spriteCloud's Performance Testing
    Given I open "/"
    When I click the link "Performance Testing"
    Then I see the heading "That's when they leave."
    Then I see the heading "Performance is a revenue conversation."
