# Generated by quail. Declarative view of the op-list journey.
Feature: Explore performance testing page

  @journey:composed @smoke
  Scenario: Explore performance testing page
    Given I open "/"
    When I click the link "Performance Testing"
