# Generated by quail. Declarative view of the op-list journey.
Feature: Explore spriteCloud Test Automation

  @journey:composed @smoke
  Scenario: Explore spriteCloud Test Automation
    Given I open "/"
    When I click the link "Test Automation"
    When I click the link "Testing Services"
    When I click the link "Functional Testing"
    When I click the link "Case Studies"
    Then I see the heading "Ready to talk?"
