# Generated by quail. Declarative view of the op-list journey.
Feature: rejects empty contact form submission

  @journey:negative @smoke
  Scenario: rejects empty contact form submission
    Given I open "/contact"
    When I click the button "Send message"
    Then I see the alert "Please fill out this field"
