# Generated by quail. Declarative view of the op-list journey.
Feature: rejects malformed email address

  @journey:negative @smoke
  Scenario: rejects malformed email address
    Given I open "/contact"
    When I fill "Name" with "Alex Johnson"
    When I fill "Email" with "not-an-email"
    When I click the button "Send"
    Then I see the alert "Please enter a valid email address"
