# Generated by quail. Declarative view of the op-list journey.
Feature: Rejects malformed email in contact form submission

  @journey:negative @smoke
  Scenario: Rejects malformed email in contact form submission
    Given I open "/contact"
    When I fill "First name" with "Alex"
    When I fill "Last name" with "Kim"
    When I fill "Email address" with "not-an-email"
    When I fill "Company" with "TechCorp"
    When I fill "What are you interested in?" with "Test Automation"
    When I fill "What's the situation?" with "We need help automating our regression suite."
    When I click the button "Send message"
    Then I see the alert "Please enter a valid email address"
