# Generated by quail. Declarative view of the op-list journey.
Feature: rejects empty email field

  @journey:negative @smoke
  Scenario: rejects empty email field
    Given I open "/careers"
    When I click the link "Test Automation Engineer"
    When I click the button "Apply Now"
    When I fill "Full Name" with "Jordan Lee"
    When I fill "Email" with ""
    When I click the button "Submit Application"
    Then I see the alert "Email is required"
