# Generated by quail. Declarative view of the op-list journey.
Feature: Explore case study on PostNL

  @journey:composed @smoke
  Scenario: Explore case study on PostNL
    Given I open "/"
    When I click the link "Case Studies"
    When I click the link "One test framework for seven PostNL teams"
