# Generated by quail. Declarative view of the op-list journey.
Feature: Researching spriteCloud services and case studies

  @journey:composed @smoke
  Scenario: Researching spriteCloud services and case studies
    Given I open "/"
    When I click the link "Case Studies"
    When I click the link "One test framework for seven PostNL teams"
