# Generated by quail. Declarative view of the op-list journey.
Feature: Explore PostNL case study

  @journey:composed @smoke
  Scenario: Explore PostNL case study
    Given I open "/"
    When I click the link "Case Studies"
    When I click the link "One test framework for seven PostNL teams"
    Then I see the heading "One test framework for seven PostNL teams"
