# Generated by quail. Declarative view of the op-list journey.
Feature: Explore SpriteCloud's Case Study

  @journey:composed @smoke
  Scenario: Explore SpriteCloud's Case Study
    Given I open "/"
    When I click the link "Case Studies"
    When I click the link "citizenM — Case Study"
