# Generated by quail. Declarative view of the op-list journey.
Feature: Contact sales with specific service interest

  @journey:suite @smoke
  Scenario: Contact sales with specific service interest
    Given I open "/contact"
    When I fill "Which service are you interested in" with "Test Automation"
    When I click the button "Submit"
