# Generated by quail. Declarative view of the op-list journey.
Feature: Browse careers and review a job posting

  @journey:suite @smoke
  Scenario: Browse careers and review a job posting
    Given I open "/"
    When I click the menuitem "Company"
    When I click the link "Careers"
    When I click the link "Test Automation Engineer"
    Then I see the main "Test Automation Engineer"
