# Generated by quail. Declarative view of the op-list journey.
Feature: Filter contact form for Test Automation

  @journey:suite @smoke
  Scenario: Filter contact form for Test Automation
    Given I open "/contact"
    When I click the combobox "Which service are you interested in"
    When I click the option "Test Automation"
    When I fill "Name" with "Alex"
    When I fill "Email" with "alex@example.com"
    When I press "Enter"
