# Generated by quail. Declarative view of the op-list journey.
Feature: Browse company story via cases and press team

  @journey:suite @smoke
  Scenario: Browse company story via cases and press team
    Given I open "/"
    When I click the link "Work"
    When I click the link "Oikocredit"
    When I click the link "SpriteCloud"
    Then I see the heading "About"
