# Generated by quail. Declarative view of the op-list journey.
Feature: Toggle service menu and verify all services appear

  @journey:suite @smoke
  Scenario: Toggle service menu and verify all services appear
    Given I open "/test-automation"
    When I click the menuitem "Testing Services"
    When I click the link "Functional Testing"
    When I click the link "Test Automation"
    When I click the link "Performance Testing"
    When I click the link "Cybersecurity & Penetration Testing"
    Then I see the heading "Cybersecurity & Penetration Testing"
