# Generated by quail. Declarative view of the op-list journey.
Feature: Contact the team via the contact form

  @journey:suite @smoke
  Scenario: Contact the team via the contact form
    Given I open "/contact"
    When I fill "Name" with "Alex Johnson"
    When I fill "Email" with "alex@example.com"
    When I fill "Message" with "Interested in test automation for our fintech platform."
    When I click the button "Send Message"
    Then I see the heading "Thank you for your message"
