# Generated by quail. Declarative view of the op-list journey.
Feature: Comparing two case studies side-by-side content

  @journey:suite @smoke
  Scenario: Comparing two case studies side-by-side content
    Given I open "/case-study/oikocredit"
    When I click the link "PostNL"
    Then I see the heading "PostNL"
