# Generated by quail. Declarative view of the op-list journey.
Feature: Apply for current job posting via direct careers link

  @journey:suite @smoke
  Scenario: Apply for current job posting via direct careers link
    Given I open "/careers"
    When I click the link "Test Automation Engineer"
