# Generated by quail. Declarative view of the op-list journey.
Feature: Compare two case studies on mobile readiness

  @journey:suite @smoke
  Scenario: Compare two case studies on mobile readiness
    Given I open "/work"
    When I click the link "Oikocredit"
    When I click the link "Home"
    When I open "/case-study/citizenm"
    Then I see the heading "citizenM"
