# Generated by quail. Declarative view of the op-list journey.
Feature: Review single case study detail in depth

  @journey:suite @smoke
  Scenario: Review single case study detail in depth
    Given I open "/case-study/oikocredit"
    Then I see the heading "Oikocredit"
    When I click the link "Testing Services"
    Then I see the heading "Testing Services"
    When I click the link "Performance Testing"
    Then I see the heading "Performance Testing"
