# Generated by quail. Declarative view of the op-list journey.
Feature: Quickly verify service specialties from homepage menu

  @journey:suite @smoke
  Scenario: Quickly verify service specialties from homepage menu
    Given I open "/"
    When I click the menuitem "Testing Services"
    Then I see the heading "Testing Services"
    When I click the link "Functional Testing"
    Then I see the heading "Functional Testing"
