# Generated by quail. Declarative view of the op-list journey.
Feature: Quickly locate the careers form from homepage

  @journey:suite @smoke
  Scenario: Quickly locate the careers form from homepage
    Given I open "/"
    When I click the link "Careers"
    Then I see the heading "Careers"
