# Generated by quail. Declarative view of the op-list journey.
Feature: Jump from case study to specific service details

  @journey:suite @smoke
  Scenario: Jump from case study to specific service details
    Given I open "/case-study/oikocredit"
    When I click the link "Test Automation"
    Then I see the heading "Test Automation"
