# Generated by quail. Declarative view of the op-list journey.
Feature: Browse all case studies, then spot-check ecommerce one

  @journey:suite @smoke
  Scenario: Browse all case studies, then spot-check ecommerce one
    Given I open "/work"
    When I click the link "eCommerce platform"
    Then I see the heading "eCommerce platform"
