# Generated by quail. Declarative view of the op-list journey.
Feature: Rapidly jump from homepage to an event details page

  @journey:suite @smoke
  Scenario: Rapidly jump from homepage to an event details page
    Given I open "/"
    When I click the menuitem "Company"
    When I click the link "Events"
    When I click the link "Barcelona IT Community Meetup May 2026"
