# Generated by quail. Declarative view of the op-list journey.
Feature: Navigate back mid-careers application

  @journey:suite @smoke
  Scenario: Navigate back mid-careers application
    Given I open "/careers"
    When I click the link "HR Internship"
    When I click the button "Apply Now"
    When I press "Escape"
    When I click the button "Back"
