# Generated by quail. Declarative view of the op-list journey.
Feature: Exploring company info and current openings

  @journey:suite @smoke
  Scenario: Exploring company info and current openings
    Given I open "/"
    When I click the menuitem "Company"
    When I click the link "About"
    Then I see the heading "About"
    When I click the link "Careers"
    Then I see the heading "Careers"
    When I click the link "Test Automation Engineer"
    Then I see the heading "Test Automation Engineer"
