# Generated by quail. Declarative view of the op-list journey.
Feature: Contact sales with vague interest using service filter

  @journey:suite @smoke
  Scenario: Contact sales with vague interest using service filter
    Given I open "/contact"
    When I fill "Which service are you interested in" with "Test Automation"
    When I fill "Name" with "Alex Chen"
    When I fill "Email" with "alex@example.com"
    When I fill "Message" with "We’re exploring automation options"
    When I press "Enter"
    Then I see the heading "Thank you"
