# Generated by quail. Declarative view of the op-list journey.
Feature: Explore case studies by navigation

  @journey:suite @smoke
  Scenario: Explore case studies by navigation
    Given I open "/"
    When I click the link "Work"
    When I click the link "Oikocredit"
    Then I see the heading "Oikocredit"
