# Generated by quail. Declarative view of the op-list journey.
Feature: Evaluate team credibility via About and Careers

  @journey:suite @smoke
  Scenario: Evaluate team credibility via About and Careers
    Given I open "/"
    When I click the link "About"
    Then I see the heading "About"
    When I click the link "Careers"
    When I click the link "Test Automation Engineer"
    Then I see the heading "Test Automation Engineer"
    When I click the link "HR Internship – Process & People"
    Then I see the heading "HR Internship – Process & People"
