# Generated by quail. Declarative view of the op-list journey.
Feature: Review careers page, then click into a specific vacancy

  @journey:suite @smoke
  Scenario: Review careers page, then click into a specific vacancy
    Given I open "/careers"
    When I click the link "Test Automation Engineer"
    Then I see the heading "Test Automation Engineer"
