# Generated by quail. Declarative view of the op-list journey.
Feature: Compare performance testing page to main homepage

  @journey:suite @smoke
  Scenario: Compare performance testing page to main homepage
    Given I open "/"
    When I click the link "Performance Testing"
    When I click the link "Testing Services"
    When I click the link "Performance Testing"
    Then I see the heading "Performance Testing"
