# Generated by quail. Declarative view of the op-list journey.
Feature: View all services on the centralized services page

  @journey:suite @smoke
  Scenario: View all services on the centralized services page
    Given I open "/services"
    Then I see the heading "Testing Services"
    When I click the link "Functional Testing"
    Then I see the heading "Functional Testing"
    When I click the link "Testing Services"
    Then I see the heading "Testing Services"
