# Generated by quail. Declarative view of the op-list journey.
Feature: Explore cybersecurity offerings

  @journey:suite @smoke
  Scenario: Explore cybersecurity offerings
    Given I open "/"
    When I click the link "Cybersecurity & Penetration Testing"
    Then I see the heading "Cybersecurity & Penetration Testing"
