# Generated by quail. Declarative view of the op-list journey.
Feature: Explore a specific case study in depth

  @journey:suite @smoke
  Scenario: Explore a specific case study in depth
    Given I open "/"
    When I click the link "Work"
    When I click the link "PostNL"
    Then I see the heading "PostNL"
