# Generated by quail. Declarative view of the op-list journey.
Feature: Discover core services and visit careers

  @journey:suite @smoke
  Scenario: Discover core services and visit careers
    Given I open "/"
    When I click the link "Testing Services"
    When I click the link "Test Automation"
    When I click the link "Careers"
    Then I see the heading "Careers"
