# Generated by quail. Declarative view of the op-list journey.
Feature: Registers for an upcoming QA meetup

  @journey:suite @smoke
  Scenario: Registers for an upcoming QA meetup
    Given I open "/"
    When I click the menuitem "Company"
    When I click the link "Events"
    When I click the link "Barcelona IT Community Meetup May 2026"
    When I fill "Name" with "Alex Tester"
    When I fill "Email" with "alex@example.com"
    When I click the button "Register"
