# Generated by quail. Declarative view of the op-list journey.
Feature: Follow a non-obvious path from homepage to open jobs via Company menu

  @journey:suite @smoke
  Scenario: Follow a non-obvious path from homepage to open jobs via Company menu
    Given I open "/"
    When I click the menuitem "Company"
    When I click the link "Careers"
    When I click the link "Test Automation Engineer"
    When I click the link "HR Internship"
