# Generated by quail. Declarative view of the op-list journey.
Feature: Submit a service inquiry with filter selection

  @journey:suite @smoke
  Scenario: Submit a service inquiry with filter selection
    Given I open "/contact"
    When I fill "Which service are you interested in" with "Functional Testing"
    When I fill "Name" with "Alex Johnson"
    When I fill "Email" with "alex@example.com"
    When I fill "Message" with "We need functional testing for our web app."
    When I press "Enter"
    Then I see the heading "Thank You"
