# Generated by quail. Declarative view of the op-list journey.
Feature: Review a case study and return to homepage via services

  @journey:suite @smoke
  Scenario: Review a case study and return to homepage via services
    Given I open "/"
    When I click the link "Work"
    When I click the link "BEN"
    When I click the link "Testing Services"
    Then I see the heading "Testing Services"
