# Generated by quail. Declarative view of the op-list journey.
Feature: Skim homepage for company description

  @journey:suite @smoke
  Scenario: Skim homepage for company description
    Given I open "/"
    Then I see the main "QA & Software Testing Consultancy"
    Then I see the heading " spriteCloud helps teams build better software through expert QA and testing."
