# Generated by quail. Declarative view of the op-list journey.
Feature: Fill contact form twice in same tab

  @journey:suite @smoke
  Scenario: Fill contact form twice in same tab
    Given I open "/contact"
    When I fill "Name" with "Test User"
    When I fill "Email" with "test@example.com"
    When I fill "Message" with "Testing form submission"
    When I click the button "Send"
    When I click the link "Contact"
    When I fill "Name" with "Another User"
    Then I see the textbox "Name"
