# Generated by quail. Declarative view of the op-list journey.
Feature: Jump from homepage to open careers page

  @journey:suite @smoke
  Scenario: Jump from homepage to open careers page
    Given I open "/"
    When I click the menuitem "Company"
    When I click the link "Careers"
    Then I see the heading "Careers"
