# Generated by quail. Declarative view of the op-list journey.
Feature: View all case studies from homepage

  @journey:suite @smoke
  Scenario: View all case studies from homepage
    Given I open "/"
    When I click the link "Work"
    Then I see the heading "Work"
