# Generated by quail. Declarative view of the op-list journey.
Feature: Engaging with case studies to assess real-world impact

  @journey:suite @smoke
  Scenario: Engaging with case studies to assess real-world impact
    Given I open "/work"
    Then I see the heading "Work"
    When I click the link "PostNL"
    Then I see the heading "PostNL"
    When I click the link "Ben"
    Then I see the heading "Ben"
