# Generated by quail. Declarative view of the op-list journey.
Feature: Filter contact form by service interest and submit inquiry

  @journey:suite @smoke
  Scenario: Filter contact form by service interest and submit inquiry
    Given I open "/contact"
    When I fill "Which service are you interested in" with "Functional Testing"
    When I fill "Name" with "Alex Testing"
    When I fill "Email" with "alex@example.com"
    When I fill "Message" with "I’m evaluating testing partners for a legacy migration project."
    When I click the button "Submit"
