# Generated by quail. Declarative view of the op-list journey.
Feature: Browses case studies to validate capabilities

  @journey:suite @smoke
  Scenario: Browses case studies to validate capabilities
    Given I open "/"
    When I click the link "Work"
    When I click the link "PostNL"
    Then I see the heading "PostNL"
    When I click the link "Oikocredit"
