# Generated by quail. Declarative view of the op-list journey.
Feature: Exploring career opportunities and reading an open job description

  @journey:suite @smoke
  Scenario: Exploring career opportunities and reading an open job description
    Given I open "/careers"
    When I click the link "Test Automation Engineer"
    Then I see the heading "Test Automation Engineer"
