# Generated by quail. Declarative view of the op-list journey.
Feature: Skim case studies for performance testing proof

  @journey:suite @smoke
  Scenario: Skim case studies for performance testing proof
    Given I open "/performance-testing"
    When I click the link "eCommerce platform"
    Then I see the heading "Performance Testing"
    When I click the link "Oikocredit"
    Then I see the heading "Oikocredit"
