# Generated by quail. Declarative view of the op-list journey.
Feature: Quick-switch between testing service pages to compare offerings

  @journey:suite @smoke
  Scenario: Quick-switch between testing service pages to compare offerings
    Given I open "/functional-testing"
    When I click the link "Test Automation"
    When I click the link "Performance Testing"
    When I click the link "Cybersecurity & Penetration Testing"
    Then I see the heading "Cybersecurity & Penetration Testing"
