# Generated by quail. Declarative view of the op-list journey.
Feature: Browse and read first case study by default ordering

  @journey:suite @smoke
  Scenario: Browse and read first case study by default ordering
    Given I open "/work"
    When I click the link "Oikocredit"
    Then I see the heading "Oikocredit"
