# Generated by quail. Declarative view of the op-list journey.
Feature: Read multiple case studies to assess real-world impact

  @journey:suite @smoke
  Scenario: Read multiple case studies to assess real-world impact
    Given I open "/work"
    When I click the link "Oikocredit"
    When I click the link "PostNL"
    When I click the link "citizenM"
    Then I see the heading "citizenM"
