# Generated by quail. Declarative view of the op-list journey.
Feature: Skim homepage for career links then jump to HR internship

  @journey:suite @smoke
  Scenario: Skim homepage for career links then jump to HR internship
    Given I open "/"
    When I click the link "Careers"
    When I click the link "HR Internship – Process & People"
