# Generated by quail. Declarative view of the op-list journey.
Feature: Quickly compare performance and functional testing pages

  @journey:suite @smoke
  Scenario: Quickly compare performance and functional testing pages
    Given I open "/performance-testing"
    When I click the link "Functional Testing"
    When I click the link "Performance Testing"
    Then I see the heading "Performance Testing"
