# Generated by quail. Declarative view of the op-list journey.
Feature: Typo → autocorrect → submit across multiple forms

  @journey:suite @smoke
  Scenario: Typo → autocorrect → submit across multiple forms
    Given I open "/contact"
    When I fill "Name" with "Jhn Doe"
    When I fill "Email" with "jhn@example.con"
    When I press "Tab"
    When I press "Tab"
    When I press "Tab"
    When I fill "Name" with "Jane Doe"
    When I fill "Email" with "jane@example.com"
    When I click the button "Submit"
    Then I see the dialog "Thank you for your message"
