# Generated by quail. Declarative view of the op-list journey.
Feature: Quickly filter and submit contact inquiry by performance testing

  @journey:suite @smoke
  Scenario: Quickly filter and submit contact inquiry by performance testing
    Given I open "/contact"
    When I fill "Which service are you interested in" with "Performance Testing"
    When I fill "Name" with "Alex"
    When I fill "Email" with "alex@example.com"
    When I fill "Message" with "Interested in performance testing for our e-commerce platform."
    When I click the button "Submit"
