# Generated by quail. Declarative view of the op-list journey.
Feature: Visit events page and check past vs future

  @journey:suite @smoke
  Scenario: Visit events page and check past vs future
    Given I open "/events"
    Then I see the heading "Events & Meetups"
    When I click the link "QA Community Meetup April 2026"
    Then I see the heading "QA Community Meetup April 2026"
