# Generated by quail. Declarative view of the op-list journey.
Feature: From homepage, navigate to jobs and filter by role

  @journey:suite @smoke
  Scenario: From homepage, navigate to jobs and filter by role
    Given I open "/"
    When I click the link "Careers"
    When I click the heading "Test Automation Engineer"
    Then I see the main "Test Automation Engineer"
    Then I see the link "Apply now"
