# Generated by quail. Declarative view of the op-list journey.
Feature: Skim-testimonials via latest case study

  @journey:suite @smoke
  Scenario: Skim-testimonials via latest case study
    Given I open "/work"
    When I click the link "Oikocredit"
