# Generated by quail. Declarative view of the op-list journey.
Feature: Browse cybersecurity page from homepage menu

  @journey:suite @smoke
  Scenario: Browse cybersecurity page from homepage menu
    Given I open "/"
    When I click the menuitem "Testing Services"
    When I click the link "Cybersecurity"
