# Generated by quail. Declarative view of the op-list journey.
Feature: Browse case studies in bulk to compare industries

  @journey:suite @smoke
  Scenario: Browse case studies in bulk to compare industries
    Given I open "/work"
    When I click the link "Oikocredit"
    When I click the link "Back"
    When I click the link "PostNL"
    Then I see the heading "PostNL"
