# Generated by quail. Declarative view of the op-list journey.
Feature: Back-button navigation during form fill

  @journey:suite @smoke
  Scenario: Back-button navigation during form fill
    Given I open "/contact"
    When I fill "Name" with "Jane Smith"
    When I fill "Email" with "jane@example.com"
    When I open "/about"
    When I press "BackSpace"
    Then I see the heading "Contact"
