# Generated by quail. Declarative view of the op-list journey.
Feature: Compare testing services side-by-side

  @journey:suite @smoke
  Scenario: Compare testing services side-by-side
    Given I open "/services"
    When I click the link "Functional Testing"
    When I click the link "Test Automation"
    When I click the link "Performance Testing"
    When I click the link "Cybersecurity & Penetration Testing"
    Then I see the heading "Cybersecurity & Penetration Testing"
