# Generated by quail. Declarative view of the op-list journey.
Feature: Accessing cybersecurity service page

  @journey:suite @smoke
  Scenario: Accessing cybersecurity service page
    Given I open "/cybersecurity"
    When I click the link "Testing Services"
    When I click the link "Cybersecurity & Penetration Testing"
    Then I see the heading "Cybersecurity & Penetration Testing"
