# Generated by quail. Declarative view of the op-list journey.
Feature: Contact to request testing services

  @journey:suite @smoke
  Scenario: Contact to request testing services
    Given I open "/"
    When I click the link "Contact"
    When I fill "Which service are you interested in" with "Test Automation"
    When I fill "Name" with "Alex Johnson"
    When I fill "Email" with "alex@example.com"
    When I fill "Message" with "We need help automating regression for our web app."
    When I click the button "Submit"
