# Generated by quail. Declarative view of the op-list journey.
Feature: From homepage, go directly to an open test automation engineer role

  @journey:suite @smoke
  Scenario: From homepage, go directly to an open test automation engineer role
    Given I open "/"
    When I click the menuitem "Company"
    When I click the link "Careers"
    When I click the link "Test Automation Engineer"
