/** Generated by quail. Shared step definitions for the .feature files.
 *
 * The five step patterns below match the closed op-list vocabulary
 * (goto / click / fill / press / seen) 1:1 with the opGoto/opClick/
 * opFill/opPress/opSeen primitives in ./prims. Every generated
 * scenario resolves against these — no per-project overrides needed.
 *
 * Uses playwright-bdd. Wire this file into your bdd config's
 * `steps` glob.
 */
import { createBdd } from 'playwright-bdd'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

const { Given, When, Then } = createBdd()

Given('I open {string}', async ({ page }, path: string) => {
  await opGoto(page, path)
})

When('I click the {word} {string}', async ({ page }, role: string, name: string) => {
  await opClick(page, role as any, name)
})

When('I fill {string} with {string}', async ({ page }, label: string, value: string) => {
  await opFill(page, label, value)
})

When('I press {string}', async ({ page }, key: string) => {
  await opPress(page, key)
})

Then('I see the {word} {string}', async ({ page }, role: string, name: string) => {
  await opSeen(page, role as any, name)
})
