/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:composed @smoke Navigate from homepage to functional testing page', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Your launch date is set. Your test coverage isn\'t.')
  await opSeen(page, 'heading', 'End-to-end functional testing and UAT from a team that has done nothing else since 2009.')
})
