/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Submit contact form with sample data', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'First name', 'Alex')
  await opFill(page, 'Last name', 'Smith')
  await opFill(page, 'Email', 'alex.smith@example.com')
  await opFill(page, 'Phone', '+1234567890')
  await opFill(page, 'What are you interested in?', 'Test automation')
  await opFill(page, 'What\'s the situation?', 'We need help scaling our QA for a new product launch.')
  await opClick(page, 'button', 'Send message')
})
