// Generated by quail. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('ContactForm', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE) })

  test('ContactForm: contact-form is visible', async ({ page }) => {
    await expect(page.getByTestId('contact-form').first()).toBeVisible()
  })

  test('ContactForm: contact-email is visible', async ({ page }) => {
    await expect(page.getByTestId('contact-email').first()).toBeVisible()
  })

  test('ContactForm: contact-message is visible', async ({ page }) => {
    await expect(page.getByTestId('contact-message').first()).toBeVisible()
  })

  test('ContactForm: contact-preview is visible', async ({ page }) => {
    await expect(page.getByTestId('contact-preview').first()).toBeVisible()
  })

  test('ContactForm: contact-submit is visible', async ({ page }) => {
    await expect(page.getByTestId('contact-submit').first()).toBeVisible()
  })

  test('ContactForm: fills the form and submits', async ({ page }) => {
    await page.getByTestId('contact-email').first().fill('test')
    await page.getByTestId('contact-message').first().fill('35')
    await page.getByTestId('contact-submit').first().click()
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
  })
})
