/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Fill contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alex Doe')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Company', 'TestCo')
  await opFill(page, 'Phone', '+15551234567')
  await opFill(page, 'What are you interested in?', 'Test automation')
  await opFill(page, 'What\'s the situation?', 'Need help automating regression tests for our web app.')
  await opClick(page, 'button', 'Submit')
})
