/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Submit contact form on spriteCloud', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'First name', 'Alex')
  await opFill(page, 'Last name', 'Kim')
  await opFill(page, 'Email address', 'alex.kim@example.com')
  await opFill(page, 'Company', 'TechCorp')
  await opFill(page, 'What are you interested in?', 'Test Automation')
  await opFill(page, 'What\'s the situation?', 'We need help automating our regression suite.')
  await opClick(page, 'button', 'Send message')
})
