/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:coverage @smoke Verify test automation page loads', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opSeen(page, 'heading', 'Test Automation')
})
