/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:coverage @smoke Visit main services landing page', async ({ page }) => {
  await opGoto(page, '/')
  await opSeen(page, 'heading', 'QA & Software Testing Consultancy')
})
