/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit About page and verifyAbout content', async ({ page }) => {
  await opGoto(page, '/about')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'main', 'About')
})
