/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Go to test automation page', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'heading', 'Test Automation')
})
