/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit agentic testing page and verify hero', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opSeen(page, 'main', 'Agentic Testing')
})
