/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit performance testing page', async ({ page }) => {
  await opGoto(page, '/performance-testing')
  await opSeen(page, 'main', 'Performance Testing — spriteCloud')
})
