/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Go to About page and interact with menu items', async ({ page }) => {
  await opGoto(page, '/about')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'heading', 'About')
})
