/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:coverage @smoke Review functional testing page content', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opSeen(page, 'heading', 'Functional Testing')
})
