/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit about page', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'main', 'About — spriteCloud')
})
