/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Expand Company accordion', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'tab', 'Company')
})
