/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:coverage @smoke Visit Functional Testing service page', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'heading', 'Functional Testing')
})
