/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit work page', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Work')
})
