/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Navigate to about page and verify main heading', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About spriteCloud')
})
