/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit Functional Testing page and verify content', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opClick(page, 'button', 'Testing Services')
  await opSeen(page, 'heading', 'Functional Testing')
})
