/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit main page and expand Services menu', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'main', 'QA & Software Testing Consultancy — spriteCloud')
})
