/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:coverage @smoke Review performance testing page content', async ({ page }) => {
  await opGoto(page, '/performance-testing')
  await opSeen(page, 'heading', 'Performance Testing')
})
