/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit work page for case studies', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Case Studies')
})
