/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit Cybersecurity & Penetration Testing page', async ({ page }) => {
  await opGoto(page, '/cybersecurity')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
})
