/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke View Agentic Testing page details', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'heading', 'Agentic Testing')
})
