/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Visit Work page and verify case studies section', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'menuitem', 'Testing Services')
  await opSeen(page, 'main', 'Work')
})
