/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Explore about page', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About')
})
