/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:coverage @smoke Work / Case studies page visit', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'main', 'Work — spriteCloud')
})
