/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke Navigate to Cybersecurity page', async ({ page }) => {
  await opGoto(page, '/cybersecurity')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
})
