/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:coverage @smoke View performance testing offerings', async ({ page }) => {
  await opGoto(page, '/performance-testing')
  await opClick(page, 'menuitem', 'Company')
  await opSeen(page, 'heading', 'Performance Testing')
})
