/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Explore SpriteCloud services', async ({ page }) => {
  await opGoto(page, '/services')
  await opSeen(page, 'heading', 'Not a service list')
  await opClick(page, 'button', 'How we work with you')
  await opSeen(page, 'heading', 'How we work with you')
  await opSeen(page, 'heading', 'Not sure which service fits?')
  await opClick(page, 'button', 'That\'s a normal place to start')
})
