/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:composed @smoke Explore SpriteCloud Test Automation', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opClick(page, 'link', 'Find out what automation would do for your team')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Company', 'TestCo')
  await opClick(page, 'button', 'Send request')
})
