/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:composed @smoke Explore spriteCloud services', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Services')
  await opClick(page, 'link', 'QA Testing')
  await opClick(page, 'button', 'Ready to talk?')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'I\'m interested in QA consultancy services.')
  await opClick(page, 'button', 'Submit')
})
