/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:composed @smoke Explore functional testing services', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Functional Testing')
})
