/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:composed @smoke Explore QA services and initiate contact', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'button', 'Services')
  await opClick(page, 'button', 'Quality Engineering')
  await opClick(page, 'link', 'Talk to an expert')
  await opFill(page, 'First Name', 'Alex')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in QA consultancy services.')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'heading', 'Thank you')
})
