/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Explore spriteCloud Test Automation page', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test More. Spend less. Ship faster.')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Ready to talk?')
})
