/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:composed @smoke Explore Test Automation Services', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test More.Spend less.Ship faster.')
  await opSeen(page, 'heading', 'A framework your team can maintain. Not one that breaks in six months.')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Quality breaks in predictable places. We know where.')
})
