// Generated by quail. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('FaqSurface', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE) })

  test('FaqSurface: faq-surface is visible', async ({ page }) => {
    await expect(page.getByTestId('faq-surface').first()).toBeVisible()
  })

  test('FaqSurface: faq-heading is visible', async ({ page }) => {
    await expect(page.getByTestId('faq-heading').first()).toBeVisible()
  })

  test('FaqSurface: faq-search is visible', async ({ page }) => {
    await expect(page.getByTestId('faq-search').first()).toBeVisible()
  })

  test('FaqSurface: Search FAQ entries is visible', async ({ page }) => {
    await expect(page.getByLabel('Search FAQ entries').first()).toBeVisible()
  })

  test('FaqSurface: faq-list is visible', async ({ page }) => {
    await expect(page.getByTestId('faq-list').first()).toBeVisible()
  })

  test('FaqSurface: faq-empty is visible', async ({ page }) => {
    await expect(page.getByTestId('faq-empty').first()).toBeVisible()
  })

  test('FaqSurface: faq-contact-cta is visible', async ({ page }) => {
    await expect(page.getByTestId('faq-contact-cta').first()).toBeVisible()
  })

  test('FaqSurface: clicks input faq-search', async ({ page }) => {
    const target = page.getByTestId('faq-search').first()
    await target.click()
    await expect(target).toBeVisible()
  })

  test('FaqSurface: click toggles aria-expanded on input', async ({ page }) => {
    const target = page.getByTestId('faq-search').first()
    const before = await target.getAttribute('aria-expanded')
    await target.click()
    const after = await target.getAttribute('aria-expanded')
    expect(after).not.toBe(before)
  })

  test('FaqSurface: fills the form and submits', async ({ page }) => {
    await page.getByTestId('faq-search').first().fill('query')
    await page.getByTestId('faq-contact-cta').first().click()
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
  })
})
