/**
 * Generated by quail. Fuzz spec for https://www.spritecloud.com/.
 *
 * Bounded negative-coverage: each text input + interactive component
 * gets exercised with edge-case payloads (empty, very long, special
 * chars) to surface input-handling bugs the happy-path specs skip
 * over. Capped at 5 emissions per page.
 *
 * Filter: `npx playwright test --grep @fuzz`
 */
import { test, expect } from './_fixtures'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — fuzz / negative input', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('https://www.spritecloud.com/', { waitUntil: 'domcontentloaded' })
  })

  test('@fuzz @keyboard popup (Testing Services) responds to Tab + Enter', async ({ page }) => {
    const target = page.getByText(/Testing Services/i).first()
    await target.focus()
    await page.keyboard.press('Enter')
    await expect(target).toBeAttached()
  })

  test('@fuzz @keyboard popup (Company) responds to Tab + Enter', async ({ page }) => {
    const target = page.getByText(/Company/i).first()
    await target.focus()
    await page.keyboard.press('Enter')
    await expect(target).toBeAttached()
  })
})
