/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits empty contact form with required fields missing', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'button', 'Send')
})
