/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:negative @smoke rejects malformed email address', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'not-an-email')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'alert', 'Please enter a valid email address')
})
