/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:negative @smoke Rejects malformed email', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alex Doe')
  await opFill(page, 'Email', 'not-an-email')
  await opFill(page, 'Company', 'TestCo')
  await opFill(page, 'Phone', '+15551234567')
  await opFill(page, 'What are you interested in?', 'Test automation')
  await opFill(page, 'What\'s the situation?', 'Need help automating regression tests for our web app.')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'alert', 'Please enter a valid email address')
})
