/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke rejects malformed email address', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Email', 'notanemail')
  await opFill(page, 'Name', 'Alex Chen')
  await opClick(page, 'button', 'Send')
})
