/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:negative @smoke Rejects malformed email in event registration', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'not-an-email')
  await opClick(page, 'button', 'Register')
})
