/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits empty contact form', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'button', 'Submit application')
  await opSeen(page, 'alert', 'Please fill out all required fields')
})
