/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits contact form with malformed email', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Email', 'not-an-email')
  await opClick(page, 'button', 'Submit')
})
