/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke rejects empty contact form submission', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'button', 'Send message')
  await opSeen(page, 'alert', 'Please fill in all required fields')
})
