/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke Rejects empty contact registration', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'button', 'Register')
})
