/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits empty contact form', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Services')
  await opClick(page, 'link', 'QA Testing')
  await opClick(page, 'button', 'Ready to talk?')
  await opClick(page, 'button', 'Submit')
})
