/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:negative @smoke Rejects malformed email in contact form submission', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'First name', 'Alex')
  await opFill(page, 'Last name', 'Kim')
  await opFill(page, 'Email address', 'not-an-email')
  await opFill(page, 'Company', 'TechCorp')
  await opFill(page, 'What are you interested in?', 'Test Automation')
  await opFill(page, 'What\'s the situation?', 'We need help automating our regression suite.')
  await opClick(page, 'button', 'Send message')
  await opSeen(page, 'alert', 'Please enter a valid email address')
})
