/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke Rejects malformed email in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Email', 'not-an-email')
  await opFill(page, 'Which service are you interested in', 'Agentic Testing')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'alert', 'Please enter a valid email address')
})
