/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke rejects malformed email in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex Rivera')
  await opFill(page, 'Email', 'not-an-email')
  await opFill(page, 'Message', 'Testing validation.')
  await opClick(page, 'button', 'Submit')
})
