/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke Rejects malformed email in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'not-an-email')
  await opFill(page, 'Message', 'Testing validation.')
  await opClick(page, 'button', 'Send')
})
