/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits empty contact form for service inquiry', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Contact')
  await opPress(page, 'Enter')
})
