/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke Rejects submission with only service selected (missing required name/email)', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'alert', 'Please provide your name and email address.')
})
