/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke Rejects malformed email address', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Test Automation')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'not-an-email')
  await opClick(page, 'button', 'Send message')
})
