/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:negative @smoke submits empty contact form', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Contact us')
  await opClick(page, 'button', 'Send message')
  await opSeen(page, 'alert', 'Please fill in all required fields')
})
