/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke rejects empty contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'button', 'Send inquiry')
  await opSeen(page, 'alert', 'Please fill out all required fields')
})
