/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits empty contact form from cybersecurity page', async ({ page }) => {
  await opGoto(page, '/cybersecurity')
  await opClick(page, 'link', 'Contact')
  await opClick(page, 'button', 'Submit')
})
