/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits with invalid email', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Email', 'not-an-email')
  await opClick(page, 'button', 'Send message')
  await opSeen(page, 'dialog', 'Please enter a valid email address')
})
