/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke submits with invalid email', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Full name', 'Alex Smith')
  await opFill(page, 'Email address', 'not-an-email')
  await opClick(page, 'button', 'Send inquiry')
})
