/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:negative @smoke rejects malformed email', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex')
  await opFill(page, 'Email', 'not-an-email')
  await opFill(page, 'Message', 'Interested in your services.')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'alert', 'Please enter a valid email address')
})
