// Generated by quail. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('Newsletter', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE) })

  test('Newsletter: newsletter-form is visible', async ({ page }) => {
    await expect(page.getByTestId('newsletter-form').first()).toBeVisible()
  })

  test('Newsletter: newsletter-email-input is visible', async ({ page }) => {
    await expect(page.getByTestId('newsletter-email-input').first()).toBeVisible()
  })

  test('Newsletter: newsletter-signup-btn is visible', async ({ page }) => {
    await expect(page.getByTestId('newsletter-signup-btn').first()).toBeVisible()
  })

  test('Newsletter: newsletter-cadence-hint is visible', async ({ page }) => {
    await expect(page.getByTestId('newsletter-cadence-hint').first()).toBeVisible()
  })

  test('Newsletter: fills the form and submits', async ({ page }) => {
    await page.getByTestId('newsletter-email-input').first().fill('test@example.com')
    await page.getByTestId('newsletter-signup-btn').first().click()
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
  })
})
