/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Explore Oikocredit case study', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'From a failed country rollout to monthly releases across Europe')
  await opSeen(page, 'heading', 'Oiko — Impact-first financial services')
  await opSeen(page, 'heading', 'A growing product stuck in manual regression loops')
  await opSeen(page, 'heading', 'Application Health Check')
})
