/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Explore case study on Oikocredit', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Case Studies')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'From a failed country rollout to monthly releases across Europe')
})
