/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 4 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Explore citizenM case study', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Case Studies')
  await opClick(page, 'link', 'Load testing a live citizenM hotel at 200% occupancy')
  await opSeen(page, 'heading', 'Load testing a live citizenM hotel at 200% occupancy')
  await opSeen(page, 'heading', 'A hotel you operate from your phone')
})
