/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapidly find engineering vacancies by role name', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Search for jobs', 'automation')
  await opSeen(page, 'link', 'Test Automation Engineer')
})
