/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit contact form with extremely long input values', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'A very long name that exceeds typical input limits and may trigger validation errors or truncation issues — testing boundary conditions')
  await opFill(page, 'Email', 'a@b.c')
  await opFill(page, 'Message', 'Lorem ipsum dolor sit amet. ')
  await opClick(page, 'button', 'Send message')
})
