/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Join an upcoming QA meetup and register', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register')
  await opFill(page, 'First Name', 'Jordan')
  await opFill(page, 'Last Name', 'Lee')
  await opFill(page, 'Email', 'jordan.lee@example.com')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'main', 'Event Registration')
})
