/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse testing service details then explore company about', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Cybersecurity')
  await opClick(page, 'link', 'Company')
  await opClick(page, 'link', 'About')
})
