/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan careers page for non-engineer roles', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'heading', 'Careers')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
  await opSeen(page, 'link', 'View all vacancies')
})
