/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill contact form with service filter then refresh', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Refresh Test')
  await opFill(page, 'Email', 'refresh@test.com')
  await opFill(page, 'Message', 'Testing post-fill page refresh')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opPress(page, 'Enter')
  await opGoto(page, '/contact')
  await opSeen(page, 'heading', 'Contact')
})
