/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Trigger event form with empty name field', async ({ page }) => {
  await opGoto(page, '/event/qa-meetup-april-2026')
  await opClick(page, 'button', 'Register')
  await opFill(page, 'Name', '')
  await opFill(page, 'Email', 'test@example.com')
  await opPress(page, 'Enter')
})
