/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim case study titles and jump to postNL details', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opSeen(page, 'heading', 'Case Studies')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL — Case Study')
})
