/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit contact form with extremely long values', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'A very long name that exceeds typical input limits and may expose truncation or validation issues in the backend')
  await opFill(page, 'Email', 'user@example.com')
  await opFill(page, 'Message', 'This is an extremely long message designed to test how the form handles overflow, word wrapping, and form validation. It contains repeated phrases and punctuation to stress-test the field\'s behavior under pressure. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
})
