/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Jumping from homepage directly to an event page via menu', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opSeen(page, 'heading', 'Diag-formtrue-pastfalse-ctatrue')
})
