/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check service options via contact form dropdown', async ({ page }) => {
  await opGoto(page, '/contact')
  await opSeen(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'combobox', 'Which service are you interested in')
})
