/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Submit contact form with longest plausible value in subject field', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'A')
  await opFill(page, 'Email', 'test@example.com')
  await opFill(page, 'Message', 'Urgent inquiry regarding complex multi-phase migration of legacy test suite to new agentic framework—can you provide timeline for emergency sprint?')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'heading', 'Thank you')
})
