/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View service options via accordion on homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opSeen(page, 'heading', 'Functional Testing')
  await opSeen(page, 'heading', 'Test Automation')
})
