/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Skim careers page for engineering roles only', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'heading', 'Current openings')
  await opSeen(page, 'link', 'Test Automation Engineer')
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
})
