/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review a specific case study from Work page', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Work')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL')
})
