/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filtering contact inquiries by service type', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Demo User')
  await opFill(page, 'Work email', 'demo@example.com')
  await opSeen(page, 'button', 'Submit')
})
