/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filling contact form with extremely long name and service choice', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Very Long Name That Exceeds Expectations And Likely Triggers Validation Edge Cases In The Backend')
  await opFill(page, 'Email', 'user@example.com')
  await opPress(page, 'Enter')
})
