/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly compare case studies side by side', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'heading', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opGoto(page, '/case-study/postnl')
  await opSeen(page, 'heading', 'PostNL')
  await opGoto(page, '/case-study/citizenm')
  await opSeen(page, 'heading', 'citizenM')
})
