/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open event detail page in new tab and return to homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opPress(page, 'ControlOrMeta+Enter')
  await opSeen(page, 'main', 'DIAG-formtrue-pastfalse-ctatrue')
})
