/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Checking event form presence on upcoming meetup page', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opSeen(page, 'dialog', 'Register for event')
  await opSeen(page, 'link', 'Register now')
  await opSeen(page, 'button', 'Close dialog')
})
