/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Research case studies and request contact', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opSeen(page, 'heading', 'Contact — spriteCloud')
})
