/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review career openings, then return to homepage', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'link', 'Testing Services')
})
