/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Filter contact form by service interest', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Jordan Lee')
  await opFill(page, 'Email', 'j.lee@example.com')
  await opFill(page, 'Message', 'Interested in integrating test automation into our CI/CD pipeline.')
  await opClick(page, 'button', 'Send Message')
})
