/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review past event details briefly', async ({ page }) => {
  await opGoto(page, '/event/qa-meetup-march-2025')
  await opSeen(page, 'heading', 'QA Meetup March 2025')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'heading', 'QA Community Meetup April 2026')
})
