/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapid double-click on event registration button', async ({ page }) => {
  await opGoto(page, '/event/qa-meetup-april-2026')
  await opClick(page, 'button', 'Register now')
  await opClick(page, 'button', 'Register now')
  await opSeen(page, 'dialog', 'Event registration')
})
