/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Brows events and register for one', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register now')
  await opFill(page, 'First name', 'Jordan')
  await opFill(page, 'Last name', 'Smith')
  await opFill(page, 'Email', 'jordan@example.com')
  await opSeen(page, 'heading', 'Register for event')
})
