/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim job details for Test Automation Engineer role', async ({ page }) => {
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
  await opSeen(page, 'link', 'Apply now')
})
