/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Back-button mid-contact form fill', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your Name', 'Jane Smith')
  await opClick(page, 'button', 'Send')
  await opPress(page, 'BackSpace')
  await opSeen(page, 'heading', 'Contact — spriteCloud')
})
