/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Apply service filter in contact form and submit query', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Test Automation')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex.j@example.com')
  await opFill(page, 'Message', 'Need custom test automation for CI/CD pipeline')
  await opPress(page, 'Enter')
})
