/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Simultaneous tabs: open contact and careers, then navigate', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Tab 1 User')
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'About')
  await opClick(page, 'button', 'Submit')
})
