/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly switch between testing service pages from any page', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Performance Testing')
})
