/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filter job postings by role quickly', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'button', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
})
