/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Type ultra-long name in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'This is an extremely long name that exceeds typical input validation expectations and might expose HTML truncation issues, SQL injection risks, or overflow vulnerabilities — though this particular field likely only stores plain text for display purposes')
  await opFill(page, 'Email', 'long@example.com')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'dialog', 'Thank you for contacting us')
})
