/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Long-value flood fill on contact message field', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Floodtester')
  await opFill(page, 'Email', 'flood@example.com')
  await opFill(page, 'Message', 'A long filled message ')
  await opFill(page, 'Message', 'A')
})
