/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse upcoming events and filter by service interest', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
})
