/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly request a service not listed in main menu', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Agentic Testing')
  await opFill(page, 'Name', 'Alex Rivera')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in agentic testing evaluation for our CI/CDpipeline')
  await opClick(page, 'button', 'Send')
})
