/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open contact form, fill long values, then refresh mid-fill', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'A very long name that tests input field truncation and backend handling of excessive character counts without submission')
  await opFill(page, 'Email', 'very.long.email.address.that.might.exceed.maximum.length@extremelylongdomainnamethatmaycauseissuesinvalidation.example.com')
  await opFill(page, 'Message', 'This is an extremely long message designed to push the limits of the textarea field length and verify graceful degradation or truncation behavior. It includes many repeated words like lorem ipsum but also specific technical queries to ensure rich-text handling and basic text processing work correctly. Additional filler text continues here to simulate real user input exceeding reasonable boundaries.')
  await opGoto(page, '/contact')
})
