/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit contact form with extremely long values and verify validation', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'This is an extremely long name that should probably be rejected or truncated by the form validation logic because it exceeds reasonable human input limits — let\'s test how the site handles it')
  await opFill(page, 'Email', 'a@b.c')
  await opFill(page, 'Message', 'This is a very long message filled with repetitive filler text to confirm whether the contact form imposes server-side length restrictions on user input. We are testing edge case resilience. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'dialog', 'Form confirmation or validation error')
})
