/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Engage with upcoming QA community events', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opPress(page, 'Enter')
})
