/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly find contact info after scanning footer links', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Contact')
  await opSeen(page, 'heading', 'Contact Us')
})
