/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill contact form with maximum-length inputs', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your Name', 'AAAAAAAAAAAAAA...')
  await opFill(page, 'Email', 'a@b.c')
  await opFill(page, 'Message', 'This is a very long message to test input truncation and validation—repeated many times: ')
  await opFill(page, 'Subject', 'Test')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opClick(page, 'button', 'Send')
})
