/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Overfilling contact form with excessively long input', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'AAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
  await opFill(page, 'Email', 'verylongemailaddresswithnonexistentdomainbutstillshouldnotbreaktheform@example.verylongtld')
  await opFill(page, 'Message', 'A longer message to see how the field handles overflow and boundary conditions. This is a very long message with many words repeated to ensure we push past typical content length expectations without actual spam content. The goal is to test tolerance to extreme inputs and validation behavior. More text to fill the remaining space and test submit reliability.')
  await opPress(page, 'Enter')
  await opSeen(page, 'main', 'Contact')
})
