/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage to an open engineering role and back', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'link', 'Back to all careers')
  await opSeen(page, 'heading', 'Careers')
})
