/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore agentic testing and contact for consultation', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Agentic Testing')
  await opFill(page, 'Name', 'Alex Sample')
  await opFill(page, 'Email', 'alex@example.com')
  await opClick(page, 'button', 'Submit')
})
