/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-button spam from case study to homepage to events', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Contact')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'Home')
  await opPress(page, 'BackSpace')
  await opClick(page, 'link', 'Events')
  await opPress(page, 'BackSpace')
  await opSeen(page, 'heading', 'Events & Meetups')
})
