/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Fill contact form with service filter selected', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in automation assessment.')
  await opClick(page, 'button', 'Submit')
})
