/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Download and explore case study PDF', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opClick(page, 'link', 'Download case study')
  await opSeen(page, 'dialog', 'PDF download')
})
