/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill careers form twice, second time with edited data', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Initial inquiry')
  await opClick(page, 'button', 'Submit')
  await opPress(page, 'Tab')
  await opFill(page, 'Name', 'Alex Tester (updated)')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'heading', 'Thank you')
})
