/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Read a featured case study, then explore related services', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation')
})
