/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View upcoming QA community meetup with form interaction', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opFill(page, 'Name', 'Alex')
  await opFill(page, 'Email', 'alex@example.com')
  await opPress(page, 'Enter')
})
