/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore career opportunities and review an open vacancy', async ({ page }) => {
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'HR Internship – Process & People')
})
