/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Accidentally refresh contact form mid-fill', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Alex')
  await opFill(page, 'Email', 'alex@example.com')
  await opPress(page, 'Tab')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
  await opSeen(page, 'dialog', 'Oops! Something went wrong while submitting the form.')
})
