/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Hit refresh after typing into contact service filter', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Performance')
  await opPress(page, 'Tab')
  await opPress(page, 'Refresh')
  await opSeen(page, 'combobox', 'Which service are you interested in')
})
