/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim company info from homepage to about page', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Company')
  await opClick(page, 'link', 'About')
})
