/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Quickly locate the careers form from homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
})
