/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open same case study in two tabs for conflict', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Read full case study')
  await opSeen(page, 'heading', 'Oikocredit — spriteCloud Case Study')
})
