/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Refresh page after filling form fields', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your Name', 'Refrash Tester')
  await opFill(page, 'Your Email', 'refresh@test.com')
  await opFill(page, 'Your Message', 'Checking persistence after reload')
  await opPress(page, 'Tab')
  await opPress(page, 'Tab')
  await opPress(page, 'Tab')
  await opPress(page, 'Tab')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
})
