/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse case studies to validate performance testing claims', async ({ page }) => {
  await opGoto(page, '/performance-testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Work')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL')
})
