/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Refresh form page mid-fill and verify state persistence', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@example.com')
  await opPress(page, 'F5')
  await opSeen(page, 'textbox', 'Your Name')
  await opSeen(page, 'textbox', 'Email')
})
