/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate via menu accordion while refreshing mid-flow', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'option', 'Functional Testing')
  await opPress(page, 'F5')
  await opSeen(page, 'heading', 'Functional Testing')
})
