/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Switch from homepage to a specific case study via case-study listing', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'View all case studies')
  await opSeen(page, 'heading', 'Case Studies')
})
