/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Accidentally double-submit event registration', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'button', 'Register')
  await opClick(page, 'button', 'Register')
  await opClick(page, 'button', 'Register')
})
