/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore cybersecurity offering', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'main', 'Cybersecurity & Penetration Testing')
})
