/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Browse all case studies for industry examples', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Case Studies')
  await opSeen(page, 'link', 'Oikocredit')
  await opSeen(page, 'link', 'PostNL')
  await opSeen(page, 'link', 'citizenM')
})
