/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discover events and register interest', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'heading', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register')
  await opFill(page, 'Name', 'Jordan Lee')
  await opFill(page, 'Email', 'jordan@example.com')
  await opPress(page, 'Enter')
})
