/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Trying event registration flow', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'button', 'Register now')
  await opFill(page, 'First name', 'Alex')
  await opFill(page, 'Last name', 'Runner')
  await opFill(page, 'Email', 'alex@example.com')
  await opPress(page, 'Enter')
})
