/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Read a case study not yet covered via services page', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Functioneel testen voor een Nederlands bankkanaal')
  await opSeen(page, 'heading', 'Oikocredit')
})
