/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Expand Services accordion, click Test Automation, then close and re-expand', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
  await opPress(page, 'Backspace')
  await opClick(page, 'menuitem', 'Testing Services')
})
