/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Submit a contact inquiry', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Alex Sample')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'I’m interested in your functional testing services.')
  await opClick(page, 'button', 'Submit')
})
