/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapidly find test automation service details', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opSeen(page, 'heading', 'Test Automation — spriteCloud')
})
