/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit contact form for Test Automation inquiry', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'I\'d like to discuss test automation for our web app')
  await opClick(page, 'button', 'Submit')
})
