/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Review a past event’s agenda and recaps', async ({ page }) => {
  await opGoto(page, '/event/qa-meetup-march-2025')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Testing Services')
  await opSeen(page, 'link', 'Agentic Testing')
})
