/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill contact form with extreme-length inputs and submit', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'A very long name that exceeds typical field limits and may trigger validation edge cases in the backend')
  await opFill(page, 'Email', 'a@b.c')
  await opFill(page, 'Company', 'Corp')
  await opFill(page, 'Message', 'This is a very long message designed to test how the contact form handles extreme-length text input, including potential truncation or encoding issues.')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'heading', 'Thank you')
})
