/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View services, then filter contact form by interest', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Test Automation')
  await opFill(page, 'Name', 'Alex Demo')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in test automation consultancy')
  await opClick(page, 'button', 'Send')
})
