/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open and inspect raw OpenAPI spec JSON', async ({ page }) => {
  await opGoto(page, '/api/v3/openapi.json')
  await opSeen(page, 'heading', 'OpenAPI Specification')
})
