/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore case studies to evaluate real-world impact', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'main', 'PostNL — Case Study — spriteCloud')
  await opClick(page, 'link', ' citizenM')
  await opSeen(page, 'main', 'citizenM — Case Study — spriteCloud')
})
