/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Validate contact form filters by service interest', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Performance Testing')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'main', 'Contact — spriteCloud')
})
