/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check contact page form options quickly', async ({ page }) => {
  await opGoto(page, '/contact')
  await opSeen(page, 'combobox', 'Which service are you interested in')
  await opSeen(page, 'main', 'Contact')
})
