/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From home page, visit about page then check contact options', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Company')
  await opClick(page, 'link', 'About')
  await opClick(page, 'link', 'Contact')
  await opSeen(page, 'heading', 'Contact')
})
