/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Verify all service pages list same navigation links', async ({ page }) => {
  await opGoto(page, '/services')
  await opSeen(page, 'link', 'Test Automation')
  await opGoto(page, '/performance-testing')
  await opSeen(page, 'link', 'Test Automation')
  await opGoto(page, '/cybersecurity')
  await opSeen(page, 'link', 'Test Automation')
})
