/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-tapping submit on event registration', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opFill(page, 'Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@example.com')
  await opClick(page, 'button', 'Register')
  await opClick(page, 'button', 'Register')
  await opClick(page, 'button', 'Register')
  await opSeen(page, 'dialog', 'Registration submitted')
})
