/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open contact page in two tabs, submit both rapidly', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opFill(page, 'Name', 'Concurrent Browser Test')
  await opFill(page, 'Email', 'concurrent@test.com')
  await opFill(page, 'Message', 'Testing concurrent submissions')
  await opClick(page, 'button', 'Submit')
})
