/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Verify contact form service filter', async ({ page }) => {
  await opGoto(page, '/contact')
  await opSeen(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opSeen(page, 'option', 'Functional Testing')
  await opSeen(page, 'option', 'Performance Testing')
  await opSeen(page, 'option', 'Cybersecurity')
})
