/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Claim consulting lead via contact form with service filter', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alejandro')
  await opFill(page, 'Email', 'alejandro@example.com')
  await opFill(page, 'Message', 'We need functional testing for a legacy banking app upgrade.')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'heading', 'Thank you for contacting us')
})
