/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim company overview via About page', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Testing Services')
})
