/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Read a performance-case study and exit', async ({ page }) => {
  await opGoto(page, '/case-study/ecommerce-performance')
  await opSeen(page, 'heading', 'eCommerce platform')
  await opSeen(page, 'link', 'View all case studies')
})
