/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Visit test automation page and review services overview', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Testing Services')
})
