/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill and submit careers form with empty required fields', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'button', 'Apply now')
  await opFill(page, 'First name', 'Jo')
  await opPress(page, 'Tab')
  await opPress(page, 'Tab')
  await opClick(page, 'button', 'Upload file')
  await opClick(page, 'button', 'Submit application')
})
