/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigating from homepage to a specific case study', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Functional Testing')
})
