/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Evaluate company background and expertise', async ({ page }) => {
  await opGoto(page, '/about')
  await opClick(page, 'link', 'About')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Functional Testing')
})
