/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Verify service overlap between testing categories', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
})
