/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check service offerings via top menu dropdown', async ({ page }) => {
  await opGoto(page, '/about')
  await opClick(page, 'menuitem', 'Testing Services')
  await opSeen(page, 'link', 'Functional Testing')
})
