/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Learn about company mission from About page', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About spriteCloud')
  await opClick(page, 'link', 'Our story')
  await opSeen(page, 'heading', 'Our story')
})
