/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse open engineering roles to assess team fit', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
  await opClick(page, 'link', 'Apply now')
  await opSeen(page, 'dialog', 'Apply for job')
})
