/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Evaluate fit by reviewing open roles', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'link', 'HR Internship – Process & People')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
})
