/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse events and register for a future QA meetup', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register now')
  await opFill(page, 'Name', 'Alex Demo')
  await opFill(page, 'Email', 'alex@example.com')
  await opClick(page, 'button', 'Submit')
})
