/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim case study titles to find relevant industry example', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Work')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opGoto(page, '/case-study/postnl')
  await opSeen(page, 'heading', 'PostNL')
})
