/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quick scan of career page for location options', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'heading', 'Why work at spriteCloud?')
  await opSeen(page, 'heading', 'Our locations')
  await opSeen(page, 'heading', 'Benefits')
})
