/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Long-value spam test in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'A very long name that exceeds normal expectations and is intended to stress-test input validation, possibly containing many repeated characters like aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
  await opFill(page, 'Email', 'spambot@spritecloud.com')
  await opFill(page, 'Message', 'Test message with extremely long content inserted here to trigger overflow or truncation bugs without causing page crash or incorrect rendering; this is a deliberate fuzzing effort to evaluate system robustness and UX resilience under heavy input load')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'dialog', 'Thank you for contacting us')
})
