/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Open careers page in two tabs and apply from both', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'button', 'Apply now')
  await opFill(page, 'Email', 'test@example.com')
  await opFill(page, 'Message', 'Testing multi-tab application flow')
  await opSeen(page, 'heading', 'Application received')
})
