/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open careers page, then back out and click events', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Careers')
  await opPress(page, 'Alt+Left')
  await opClick(page, 'link', 'Events & Meetups')
})
