/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Join a QA community event and register', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Event details')
  await opClick(page, 'button', 'Register now')
  await opFill(page, 'First name', 'Jordan')
  await opFill(page, 'Last name', 'Smith')
  await opFill(page, 'Email', 'jordan@example.com')
  await opSeen(page, 'button', 'Submit')
})
