/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill contact form with extreme-length value and submit', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789')
  await opFill(page, 'Email', 'verylongemailaddresswithnopunctuationorextraspacestoseeifvalidationcatchesit@exampledomainverylongsubdomain.test')
  await opFill(page, 'Message', 'This is a very long message designed to test how the form handles unusually large inputs. It spans multiple lines and includes many spaces and special characters to stress test the input validation and processing. We want to ensure no truncation or errors occur on submission.')
})
