/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View case study with performance focus', async ({ page }) => {
  await opGoto(page, '/case-study/ecommerce-performance')
  await opClick(page, 'link', 'Case Study')
  await opSeen(page, 'heading', 'E-commerce platform performance improvement')
})
