/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill contact form with ultra-long service comment', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opFill(page, 'Name', 'María-Gabriela-Fernández-Rodríguez de la Cruz')
  await opFill(page, 'Email', 'maria-gabriela@example.com')
  await opFill(page, 'Message', 'A very long message to test how the system handles extreme-length inputs without truncation or validation failures — this message is intentionally lengthy and may span several sentences to validate textarea handling.')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'heading', 'Thank you')
})
