/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Register for a community meetup', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Diagnose')
  await opClick(page, 'button', 'Register')
})
