/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Double-click submit on contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Adversarial User')
  await opFill(page, 'Email', 'bad@email.com')
  await opClick(page, 'button', 'Submit')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'dialog', 'Thank you for your inquiry')
})
