/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check career page for engineering openings', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'heading', 'Careers')
  await opSeen(page, 'link', 'Test Automation Engineer')
})
