/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Filter contact form by service interest and submit inquiry', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Alex Testing')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'I’m evaluating testing partners for a legacy migration project.')
  await opClick(page, 'button', 'Submit')
})
