/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage, skip to next upcoming event and register', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'button', 'Register')
})
