/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore company section via mobile menu', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'About')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
})
