/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Investigating career opportunities', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
  await opClick(page, 'link', 'Back to careers')
  await opClick(page, 'link', 'HR Internship')
})
