/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage to event form, then back-button mid-flow', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opFill(page, 'First Name', 'Alex')
  await opPress(page, 'Tab')
  await opFill(page, 'Last Name', 'Test')
  await opPress(page, 'Backspace')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'dialog', 'Register')
})
