/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-button during event registration flow', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'button', 'Register now')
  await opFill(page, 'First name', 'Alex')
  await opPress(page, 'Tab')
  await opClick(page, 'button', 'Register now')
  await opPress(page, 'Backspace')
  await opSeen(page, 'button', 'Register now')
})
