/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Apply to QA internship from careers list', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'HR Internship – Process & People')
  await opClick(page, 'button', 'Apply now')
  await opSeen(page, 'dialog', 'Application form')
})
