/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill and submit contact form for new service inquiry', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Test Automation')
  await opFill(page, 'Name', 'Alex Developer')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in automating regression suite for e-commerce app.')
  await opClick(page, 'button', 'Submit')
})
