/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skip to a specific case study via search', async ({ page }) => {
  await opFill(page, 'Search', 'oikocredit')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Oikocredit')
})
