/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review cybersecurity offerings and compare service pages', async ({ page }) => {
  await opGoto(page, '/cybersecurity')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Performance Testing')
  await opSeen(page, 'heading', 'Performance Testing')
})
