/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open two tabs and fill the same contact form in parallel', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex Test')
  await opFill(page, 'Email', 'alex@example.com')
})
