/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-submitting contact form after navigation delay', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Adversarial User')
  await opFill(page, 'Email', 'user@example.com')
  await opClick(page, 'button', 'Submit')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
  await opSeen(page, 'dialog', 'Contact form submitted')
})
