/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review a case study, then contact for similar engagement', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'Contact')
})
