/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-click submit on careers application form', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@example.com')
  await opFill(page, 'CV Upload', '/tmp/fake.pdf')
  await opClick(page, 'button', 'Submit application')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Application Received')
})
