/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-click subscribe button on events page', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'button', 'Register now')
  await opClick(page, 'button', 'Register now')
  await opSeen(page, 'dialog', 'Registration confirmation')
})
