/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View multiple case studies quickly via navigation', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Case Studies')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'Ben')
  await opSeen(page, 'heading', 'Ben — Case Study')
})
