/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open contact form in two tabs and submit both', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alice')
  await opFill(page, 'Email', 'alice@example.com')
  await opPress(page, 'Tab')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opClick(page, 'button', 'Submit')
})
