/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore service offerings via main menu', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opSeen(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Test Automation')
})
