/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check company info via \'About\' page', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About spriteCloud')
  await opClick(page, 'link', 'Company')
})
