/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit a contact request for a specific service', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Your Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'I\'d like to discuss agile test automation for our platform.')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Thanks for reaching out!')
})
