/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Checks multiple event dates without registering', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opSeen(page, 'heading', 'Barcelona IT Community Meetup May 2026')
})
