/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Viewing a specific past event details', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA meetup November 2025')
  await opSeen(page, 'heading', 'QA meetup November 2025')
  await opSeen(page, 'dialog', 'DIAG-formtrue-pastfalse-ctatrue')
})
