/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Read engineering job details and navigate back', async ({ page }) => {
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
})
