/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Contact the team via the contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in test automation for our fintech platform.')
  await opClick(page, 'button', 'Send Message')
  await opSeen(page, 'heading', 'Thank you for your message')
})
