/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly locate all case studies from首页', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'citizenM')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'E-Commerce platform')
  await opSeen(page, 'heading', 'spriteCloud helped this client')
})
