/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Contact with pre-filtered service interest (performance)', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opFill(page, 'Your Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Request proposal for performance testing')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'heading', 'Thank you')
})
