/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke From homepage to career application flow', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'button', 'Apply Now')
  await opFill(page, 'First Name', 'Alex')
  await opFill(page, 'Email', 'alex@example.com')
  await opPress(page, 'Tab')
  await opSeen(page, 'heading', 'Thank you for applying!')
})
