/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapid tab-switch while filling contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@test.com')
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'John Smith')
  await opSeen(page, 'button', 'Submit')
})
