/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke From homepage, navigate to jobs and filter by role', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'heading', 'Test Automation Engineer')
  await opSeen(page, 'main', 'Test Automation Engineer')
  await opSeen(page, 'link', 'Apply now')
})
