/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review case studies and request consultation', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opClick(page, 'button', 'Send')
})
