/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review open role titles without clicking', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'link', 'HR Internship – Process & People')
  await opSeen(page, 'link', 'Test Automation Engineer')
})
