/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigating from homepage to specific case study', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL — Case Study — spriteCloud')
})
