/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapidly find an upcoming event with form pre-filled', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'button', 'Register now')
})
