/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View all open career listings from homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Careers')
})
