/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan case studies for performance testing proof points', async ({ page }) => {
  await opGoto(page, '/performance-testing')
  await opSeen(page, 'link', 'Read case study')
  await opGoto(page, '/case-study/ecommerce-performance')
  await opSeen(page, 'heading', 'Challenge')
  await opSeen(page, 'heading', 'Result')
  await opClick(page, 'link', 'Contact us')
})
