/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore upcoming events to engage with the community', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opSeen(page, 'dialog', 'DIAG-formtrue-pastfalse-ctatrue')
  await opClick(page, 'button', 'Register now')
})
