/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill careers form, go back, resume, and submit', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Name', 'Test User')
  await opFill(page, 'Email', 'test@example.com')
  await opClick(page, 'button', 'Upload CV')
  await opPress(page, 'Escape')
  await opPress(page, 'Backspace')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'heading', 'Careers')
})
