/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Contact to request testing services', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'We need help automating regression for our web app.')
  await opClick(page, 'button', 'Submit')
})
