/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Race to submit careers form while refreshing', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Name', 'Candidate')
  await opFill(page, 'Email', 'candidate@example.com')
  await opFill(page, 'CV', 'https://example.com/cv')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
  await opGoto(page, '/careers')
  await opClick(page, 'button', 'Submit')
})
