/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly find contact details from homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opSeen(page, 'main', 'Contact — spriteCloud')
})
