/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Evaluate company culture via careers and events', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT community meetup May 2026')
  await opSeen(page, 'heading', 'Barcelona IT community meetup May 2026')
})
