/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly submit a career application for a test automation role', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'button', 'Apply Now')
  await opFill(page, 'Full name', 'Alex Smith')
  await opFill(page, 'Email', 'alex.smith@example.com')
  await opClick(page, 'button', 'Submit')
})
