/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly find a specific case study by title', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opClick(page, 'link', 'Case Studies')
})
