/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim services overview to confirm agentic testing offering', async ({ page }) => {
  await opGoto(page, '/services')
  await opSeen(page, 'heading', 'Agentic Testing')
})
