/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse open test automation engineer role', async ({ page }) => {
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Test Automation')
})
