/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Quickly find a relevant case study by filtering', async ({ page }) => {
  await opGoto(page, '/case-study')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL — Case Study')
  await opSeen(page, 'heading', 'Automated testing for a major logistics provider')
})
