/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Verify Cybersecurity page links back to main services', async ({ page }) => {
  await opGoto(page, '/cybersecurity')
  await opClick(page, 'link', 'Performance Testing')
  await opSeen(page, 'heading', 'Performance Testing')
})
