/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review engineering career details from case study page', async ({ page }) => {
  await opGoto(page, '/case-study/postnl')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Career')
  await opSeen(page, 'heading', 'Careers')
})
