/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly access test automation service page', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opSeen(page, 'heading', 'Test Automation')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation')
})
