/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigating from homepage to a career vacancy for quick application', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'link', 'Apply now')
})
