/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-submission attempt on contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Adversarial User')
  await opFill(page, 'Email', 'test@example.com')
  await opFill(page, 'Message', 'Testing double-submit')
  await opClick(page, 'button', 'Send message')
  await opClick(page, 'button', 'Send message')
  await opSeen(page, 'main', 'Contact')
})
