/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Switch pages mid-form fill and return to form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Probing User')
  await opFill(page, 'Email', 'user@example.com')
  await opFill(page, 'Message', 'This is a message that may get lost if navigation resets state...')
  await opClick(page, 'link', 'Company')
  await opGoto(page, '/contact')
  await opSeen(page, 'heading', 'Contact')
})
