/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim events page for past events', async ({ page }) => {
  await opGoto(page, '/events')
  await opSeen(page, 'heading', 'Events & Meetups')
})
