/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate to contact page with service filters', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opPress(page, 'ArrowDown')
  await opPress(page, 'Enter')
  await opSeen(page, 'button', 'Submit')
})
