/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Reviewing company info on About + Careers pages', async ({ page }) => {
  await opGoto(page, '/about')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'link', '...')
})
