/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate careers → event → back to careers form', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'Events & Meetups')
  await opPress(page, 'Back')
  await opPress(page, 'Back')
  await opSeen(page, 'heading', 'Careers — spriteCloud')
})
