/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submitting event form after multiple refreshes', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opPress(page, 'F5')
  await opFill(page, 'Name', 'Repeated F5 User')
  await opPress(page, 'F5')
  await opClick(page, 'button', 'Register')
  await opSeen(page, 'dialog', 'form_success')
})
