/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discovering services through the main menu expandable', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opClick(page, 'link', 'Agentic Testing')
  await opSeen(page, 'heading', 'Agentic Testing')
})
