/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-button navigation across case studies after form submission', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'button', 'Download case study')
  await opPress(page, 'Escape')
  await opClick(page, 'link', 'Case Studies')
  await opClick(page, 'button', 'Back')
  await opSeen(page, 'heading', 'Oikocredit — Case Study')
})
