/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse services and filter by interest', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Agentic Testing')
  await opSeen(page, 'heading', 'Agentic Testing')
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Functional Testing')
  await opSeen(page, 'dialog', 'Contact form')
})
