/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-submit contact form with long name and URL', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Full Name', 'John the Quick-Jumping, Highly Enthusiastic QA Lead with Extra')
  await opFill(page, 'Email', 'john@example.com')
  await opFill(page, 'Company Website', 'https://www.extremely-long-and-unrealistic-url-that-might-break-validation.com/test')
  await opClick(page, 'button', 'Submit')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'heading', 'Contact')
})
