/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Inspect contact form service filter options', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opSeen(page, 'option', 'Functional Testing')
  await opSeen(page, 'option', 'Test Automation')
  await opSeen(page, 'option', 'Performance Testing')
})
