/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Read multiple case studies rapidly', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'CitizenM')
})
