/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Double-submit contact form submission attempt', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your Name', 'Alice Developer')
  await opFill(page, 'Email', 'alice@example.com')
  await opFill(page, 'Message', 'Hi, we\'d like to discuss automation for a large fintech migration.')
  await opClick(page, 'button', 'Submit')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'main', 'Contact – spriteCloud')
})
