/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill careers form with extremely long input, then submit', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'First Name', 'ThisIsAVeryLongFirstNameThatMightCauseIssuesIfUnescaped')
  await opFill(page, 'Last Name', 'ThisIsAVeryLongLastNameThatAlsoMightCauseIssuesIfUnescaped')
  await opFill(page, 'Email', 'verylongemailaddresswith100pluscharacters12345678901234567890123456789012345678901234567890ABC@example.com')
  await opClick(page, 'button', 'Submit application')
})
