/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-submit POST request form', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'button', 'Try it out')
  await opFill(page, 'petId', '1')
  await opFill(page, 'name', 'Fluffy')
  await opFill(page, 'status', 'available')
  await opClick(page, 'button', 'Execute')
  await opClick(page, 'button', 'Execute')
  await opSeen(page, 'dialog', 'Error')
})
