/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Read agentic testing page details', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opSeen(page, 'heading', 'Agentic Testing')
})
