/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan events page for past vs upcoming', async ({ page }) => {
  await opGoto(page, '/events')
  await opSeen(page, 'heading', 'Events & Meetups')
  await opSeen(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'link', 'Barcelona IT Community Meetup May 2026')
})
