/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim main page for service summaries then drill into test automation', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation')
})
