/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Review a case study and return to homepage via services', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opClick(page, 'link', 'BEN')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Testing Services')
})
