/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Review cybersecurity testing content and service depth', async ({ page }) => {
  await opGoto(page, '/cybersecurity')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Cybersecurity')
  await opSeen(page, 'dialog', 'Contact form with cybersecurity selected')
})
