/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill contact form with very long input values', async ({ page }) => {
  await opFill(page, 'Message', 'A very very very long message content that extends well beyond normal user input to test handling of large text blocks, possibly spanning paragraphs or using repeated tokens to challenge server-side validation and client-side rendering.')
  await opPress(page, 'Enter')
  await opSeen(page, 'main', 'Contact form submission processed')
})
