/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discover agentic testing and compare it with test automation', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Agentic Testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Work')
  await opSeen(page, 'heading', 'Work')
})
