/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Register for upcoming industry event', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opFill(page, 'First Name', 'Alex')
  await opFill(page, 'Last Name', 'Dev')
  await opFill(page, 'Email', 'alex@example.com')
  await opPress(page, 'Enter')
})
