/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quick-check form in contact page dropdown options', async ({ page }) => {
  await opGoto(page, '/contact')
  await opSeen(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opPress(page, 'ArrowDown')
  await opPress(page, 'Enter')
  await opSeen(page, 'main', 'Contact — spriteCloud')
})
