/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly submit the contact form with service filter', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in functional testing for web app')
  await opClick(page, 'button', 'Send')
})
