/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Reviews consulting expertise via case studies and service pages', async ({ page }) => {
  await opGoto(page, '/case-study/ben-nl')
  await opClick(page, 'link', 'Testing Services')
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
})
