/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly verify case study formats', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Case Studies')
  await opSeen(page, 'heading', 'Case Studies')
  await opSeen(page, 'heading', 'Oikocredit')
  await opSeen(page, 'heading', 'PostNL')
})
