/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan performance testing page for methodology', async ({ page }) => {
  await opGoto(page, '/performance-testing')
})
