/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check case study format and structure', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opSeen(page, 'heading', 'Challenge')
  await opSeen(page, 'heading', 'Solution')
  await opSeen(page, 'heading', 'Results')
})
