/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-button abuse in form flow', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opFill(page, 'Name', 'Adversarial User')
  await opFill(page, 'Email', 'adversary@example.com')
  await opClick(page, 'button', 'Register')
  await opPress(page, 'Back')
})
