/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Comparing case studies by scanning headings', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Oikocredit')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL')
  await opClick(page, 'link', 'citizenM')
  await opSeen(page, 'heading', 'citizenM')
})
