/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Jump from case study list to detailed event page', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Events & Meetups')
  await opSeen(page, 'heading', 'Events & Meetups')
})
