/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim functional testing page for key claims', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opSeen(page, 'heading', 'Functional Testing')
  await opSeen(page, 'heading', 'Why functional testing matters')
  await opSeen(page, 'link', 'Request a consultation')
})
