/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Switch between services using top navigation on any service page', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Cybersecurity')
  await opSeen(page, 'main', 'Cybersecurity & Penetration Testing — spriteCloud')
})
