/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Try duplicate event registration in rapid succession', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opClick(page, 'button', 'Register now')
  await opGoto(page, '/event/qa-meetup-march-2025')
  await opClick(page, 'button', 'Register now')
  await opSeen(page, 'dialog', 'Registration form')
})
