/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View case study on e-commerce performance from Services page', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'eCommerce platform')
})
