/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan case study titles on work page', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Work')
  await opSeen(page, 'heading', 'Oikocredit')
  await opSeen(page, 'heading', 'PostNL')
  await opSeen(page, 'heading', 'citizenM')
})
