/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Back-button navigation during form fill', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Jane Smith')
  await opFill(page, 'Email', 'jane@example.com')
  await opGoto(page, '/about')
  await opPress(page, 'BackSpace')
  await opSeen(page, 'heading', 'Contact')
})
