/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan company case studies for agentic testing references', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opSeen(page, 'link', 'Testing Services')
  await opSeen(page, 'link', 'Functional Testing')
  await opSeen(page, 'link', 'Test Automation')
  await opSeen(page, 'link', 'Performance Testing')
})
