/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Try registering twice in rapid succession for same event', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opFill(page, 'Name', 'Taylor')
  await opFill(page, 'Email', 'taylor@example.com')
  await opClick(page, 'button', 'Register')
  await opClick(page, 'button', 'Register')
  await opSeen(page, 'dialog', 'Registration confirmation')
})
