/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View all case studies from homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opSeen(page, 'heading', 'Work')
})
