/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-submit contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@example.com')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opClick(page, 'button', 'Submit')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'main', 'Contact — spriteCloud')
})
