/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review a case study, then check upcoming events', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'QA community meetup')
  await opSeen(page, 'heading', 'Qa Community Meetup April 2026')
})
