/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browses events archive by visiting past events via homepage menu', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'heading', 'QA Community Meetup April 2026')
})
