/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discover company values through about and careers pages', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
  await opSeen(page, 'heading', 'Work with us')
  await opClick(page, 'link', 'HR Internship')
})
