/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore upcoming events beyond meetup registration', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup - April 2026')
  await opSeen(page, 'heading', 'QA Community Meetup - April 2026')
  await opClick(page, 'link', 'Barcelona IT Community Meetup - May 2026')
  await opSeen(page, 'heading', 'Barcelona IT Community Meetup - May 2026')
})
