/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Event registration via back-button navigation', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'button', 'Register now')
  await opFill(page, 'Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@example.com')
  await opPress(page, 'Enter')
  await opPress(page, 'Backspace')
  await opClick(page, 'link', 'Events & Meetups')
  await opSeen(page, 'heading', 'Events & Meetups')
})
