/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View services overview page to confirm service list', async ({ page }) => {
  await opGoto(page, '/services')
  await opSeen(page, 'link', 'Functional Testing')
  await opSeen(page, 'link', 'Cybersecurity & Penetration Testing')
})
