/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-click submit on contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Testing User')
  await opFill(page, 'Email', 'test@example.com')
  await opClick(page, 'button', 'Submit')
  await opPress(page, 'Enter')
  await opSeen(page, 'main', 'Contact')
})
