/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open careers form in new tab, fill in parallel', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'HR Internship')
  await opClick(page, 'button', 'Apply now')
  await opFill(page, 'Name', 'Jordan')
  await opFill(page, 'Email', 'jordan@example.com')
  await opFill(page, 'Message', 'I\'d love to intern')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
  await opSeen(page, 'dialog', 'Thank you for your application')
})
