/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open service listing then back out to homepage', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Functional Testing')
  await opPress(page, 'Back')
})
