/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Refresh events page mid-scroll', async ({ page }) => {
  await opGoto(page, '/events')
  await opFill(page, 'Search events', 'QA')
  await opPress(page, 'Enter')
  await opClick(page, 'link', 'QA community meetup')
  await opGoto(page, '/events')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Events & Meetups — spriteCloud')
})
