/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back button mid-career-application flow', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'button', 'Apply now')
  await opClick(page, 'button', 'Back')
  await opSeen(page, 'heading', 'Careers — spriteCloud')
})
