/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Navigate from homepage to contact form', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@example.com')
  await opFill(page, 'Message', 'Interested in your QA services.')
  await opSeen(page, 'button', 'Send')
})
