/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Quickly check career details by clicking a vacancy link from events page', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'HR Internship')
  await opSeen(page, 'heading', 'HR Internship')
})
