/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage to a specific case study using top navigation', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
})
