/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore a case study and contact the team', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opClick(page, 'button', 'Submit')
})
