/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim case studies for agentic testing mentions', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Case Studies')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation')
})
