/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Contact sales by selecting a service in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opPress(page, 'ArrowDown')
  await opPress(page, 'Enter')
  await opFill(page, 'Name', 'Guest User')
  await opFill(page, 'Email', 'guest@example.com')
  await opPress(page, 'Tab')
  await opSeen(page, 'button', 'Send message')
})
