/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Go back after filling contact form, then re-fill', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alex')
  await opFill(page, 'Email', 'alex@example.com')
  await opClick(page, 'link', '← Back')
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alex Smith')
  await opFill(page, 'Email', 'alex.smith@example.com')
  await opClick(page, 'button', 'Send')
})
