/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quick check of available career vacancy details', async ({ page }) => {
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Career opportunities')
})
