/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discover agentic testing as a novel service', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Agentic Testing')
  await opSeen(page, 'heading', 'Agentic Testing')
})
