/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-submitting event registration form', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opClick(page, 'button', 'Register')
  await opFill(page, 'Name', 'Ada Lovelace')
  await opFill(page, 'Email', 'ada@lovelace.org')
  await opClick(page, 'button', 'Register')
  await opClick(page, 'button', 'Register')
})
