/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapidly toggle between services and careers from homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Event')
  await opSeen(page, 'heading', 'Events & Meetups')
})
