/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Visit an upcoming event page, then register interest', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'button', 'Register interest')
  await opFill(page, 'Name', 'Jordan Tester')
  await opFill(page, 'Email', 'jordan@example.com')
  await opClick(page, 'button', 'Submit')
})
