/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Cross-check event date info and registration form', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opSeen(page, 'heading', 'QA Community Meetup - April 2026')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Testing Services')
  await opClick(page, 'link', 'Events &Meetups')
  await opSeen(page, 'heading', 'Events & Meetups')
})
