/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage, explore a case study related to performance testing', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'eCommerce platform')
  await opSeen(page, 'heading', 'eCommerce platform')
})
