/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate to careers from events page and scan internships', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'HR Internship – Process & People')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
})
