/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check event details and register for QA meetup', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup — April 2026')
  await opSeen(page, 'heading', 'QA Community Meetup — April 2026')
  await opClick(page, 'button', 'Register now')
  await opSeen(page, 'dialog', 'Event registration')
})
