/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan case studies for cybersecurity relevance', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
})
