/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse agentic testing page and compare with other services', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Functional Testing')
})
