/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore service details and contact', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex Developer')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'I\'m evaluating your automation services for our e-commerce platform.')
  await opClick(page, 'button', 'Send')
})
