/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explores events and registers interest in upcoming meetup', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opFill(page, 'What is your name?', 'ALEX')
  await opFill(page, 'Email address', 'alex@example.com')
  await opClick(page, 'button', 'Register')
})
