/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse company events across multiple pages', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA community meetup april 2026')
  await opClick(page, 'link', 'Back to all events')
  await opClick(page, 'link', 'Barcelona IT community meetup may 2026')
})
