/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Compare two service pages using navigation', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opSeen(page, 'heading', 'Performance Testing')
})
