/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Refresh careers form page after partial input', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Your Name', 'Jordan')
  await opFill(page, 'Email', 'jordan@test.io')
  await opPress(page, 'Tab')
  await opFill(page, 'Message', 'Interested in test automation engineer role.')
  await opPress(page, 'F5')
  await opSeen(page, 'main', 'Careers – spriteCloud')
})
