/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Cross-reference Agentic Testing service with case studies', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL')
})
