/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Discover core services and visit careers', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
})
