/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Accessing career details via direct URL', async ({ page }) => {
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer — Careers — spriteCloud')
})
