/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan events index for format cues', async ({ page }) => {
  await opGoto(page, '/events')
  await opSeen(page, 'heading', 'Events & Meetups')
  await opSeen(page, 'heading', 'QA Community Meetup March 2025')
  await opSeen(page, 'heading', 'Barcelona IT Community Meetup May 2026')
})
