/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Visiting a single case study to check format only', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opSeen(page, 'main', 'Case Study — spriteCloud')
})
