/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Type unusually long service filter input in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing automation with AI agents and quantum-resistant cryptography for edge computing devices, covering load testing, security scanning, and hybrid cloud validation.')
  await opFill(page, 'Name', 'Long Filter Tester')
  await opFill(page, 'Email', 'long@filter.test')
  await opClick(page, 'button', 'Submit')
})
