/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review a case study and request consultation', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opSeen(page, 'heading', 'Contact')
})
