/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Compare three testing service pages side-by-side', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
})
