/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim upcoming events and jump to latest past event page', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup - April 2026')
  await opClick(page, 'link', 'QA Community Meetup - April 2026')
  await opSeen(page, 'link', 'QA Community Meetup - April 2026')
})
