/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Trigger multiple form submissions mid-back', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Test User')
  await opFill(page, 'Email', 'test@example.com')
  await opFill(page, 'Message', 'Testing rapid resubmission')
  await opClick(page, 'button', 'Submit')
  await opPress(page, 'Back')
  await opPress(page, 'Back')
  await opClick(page, 'button', 'Submit')
})
