/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Learn more about the company team and mission', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
})
