/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review service details and investigate about the company', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'About')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Case Study')
  await opSeen(page, 'link', 'Case Study')
})
