/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate full service menu to compare offerings', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opSeen(page, 'link', 'Functional Testing')
  await opSeen(page, 'link', 'Test Automation')
  await opSeen(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Services')
  await opSeen(page, 'heading', 'Testing Services')
})
