/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Evaluate agentic testing as a novel offering', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opClick(page, 'link', 'Agentic Testing')
  await opSeen(page, 'heading', 'Agentic Testing')
})
