/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skimming company values from About page', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About')
  await opSeen(page, 'main', 'About — spriteCloud')
})
