/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate to an event page, then fill and submit its form', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opClick(page, 'link', 'Register now')
  await opFill(page, 'Name', 'Adversarial User')
  await opFill(page, 'Email', 'test@example.com')
  await opFill(page, 'Company', 'TestCorp')
  await opPress(page, 'Enter')
})
