/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check upcoming events and register interest', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Events')
  await opSeen(page, 'heading', 'Events & Meetups')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex@example.com')
  await opPress(page, 'Enter')
})
