/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse next upcoming QA meetup event', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opFill(page, 'First Name', 'Jordan')
  await opFill(page, 'Last Name', 'Dev')
  await opFill(page, 'Email', 'jordan@example.com')
  await opClick(page, 'button', 'Register')
})
