/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim homepage for case study preview cards', async ({ page }) => {
  await opGoto(page, '/')
  await opSeen(page, 'link', 'Oikocredit')
  await opSeen(page, 'link', 'PostNL')
  await opSeen(page, 'link', 'citizenM')
})
