/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Register for upcoming QA meetup', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register now')
  await opFill(page, 'First Name', 'Alex')
  await opFill(page, 'Last Name', 'Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opSeen(page, 'button', 'Submit')
})
