/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigating to a specific case study via services hub', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'eCommerce platform')
  await opSeen(page, 'heading', 'eCommerce platform — Case Study — spriteCloud')
})
