/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Confirm service dropdown appears on contact page', async ({ page }) => {
  await opGoto(page, '/contact')
  await opSeen(page, 'combobox', 'Which service are you interested in')
  await opSeen(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'link', 'Functional Testing')
})
