/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly verify QA consultancy expertise via homepage hero section', async ({ page }) => {
  await opGoto(page, '/')
  await opSeen(page, 'heading', 'QA & Software Testing Consultancy')
  await opSeen(page, 'heading', 'Future-proof your software with human-centered QA')
})
