/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Browse open roles beyond the main careers page', async ({ page }) => {
  await opGoto(page, '/vacancy/test-automation-engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
})
