/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly verify event format from list to detail page', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community MeetupMay 2026')
  await opSeen(page, 'heading', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'link', 'Events & Meetups')
  await opSeen(page, 'heading', 'Events & Meetups')
})
