/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Jump from case study to related service page', async ({ page }) => {
  await opGoto(page, '/case-study/postnl')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation — spriteCloud')
})
