/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-buttoning through nested event pages', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup - April 2026')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'QA Community Meetup - April 2026')
  await opClick(page, 'link', 'Past Events')
  await opSeen(page, 'link', 'Events & Meetups')
})
