/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore agentic testing as a modern QA approach', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opSeen(page, 'heading', 'Agentic Testing')
  await opClick(page, 'link', 'Working with AI agents')
  await opClick(page, 'link', 'Learn how it works')
  await opSeen(page, 'heading', 'Agentic Testing in Practice')
})
