/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browses testing services, then careers page', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'About')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
})
