/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Skim case study list to verify industry examples', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Case studies')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opClick(page, 'link', 'Back to case studies')
})
