/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapidly compare two case studies side by side', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'citizenM')
  await opSeen(page, 'heading', 'citizenM')
})
