/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Repeated double-click on service accordion to test race condition', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'menuitem', 'Testing Services')
  await opSeen(page, 'link', 'Test Automation')
})
