/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan recent case study for cybersecurity application', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
})
