/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse all company-related case studies', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Case Studies')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'main', 'PostNL — Case Study — spriteCloud')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'main', 'Oikocredit — Case Study — spriteCloud')
})
