/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Complete contact form with service filter as returning user', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@Tester.com')
  await opSeen(page, 'button', 'Send')
})
