/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Review cybersecurity testing offerings', async ({ page }) => {
  await opGoto(page, '/cybersecurity')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing')
})
