/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore job openings and back-button to previous page', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'HR Internship – Process & People')
  await opClick(page, 'link', 'Back')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'link', 'Back')
  await opSeen(page, 'heading', 'Careers')
})
