/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate events page, open event in new tab, then refresh original tab', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opGoto(page, '/events')
  await opSeen(page, 'heading', 'Events & Meetups')
})
