/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Quickly find a career by job title keyword', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Search', 'automation')
  await opPress(page, 'Enter')
  await opSeen(page, 'link', 'Test Automation Engineer')
})
