/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filter contact form by specific service', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opClick(page, 'button', 'Contact us')
  await opSeen(page, 'dialog', 'Thank you')
})
