/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open same contact page in two tabs and fill both', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your Name', 'Alice')
  await opFill(page, 'Your Email', 'alice@example.com')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
})
