/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Go from homepage to a past event page via Events', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
})
