/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Bounce between service pages quickly with back button', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opPress(page, 'Back')
  await opClick(page, 'link', 'Functional Testing')
  await opPress(page, 'Back')
  await opSeen(page, 'link', 'Test Automation')
})
