/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse case studies by industry relevance', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'spriteCloud')
  await opSeen(page, 'heading', 'spriteCloud')
})
