/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Preview event and jump to case study', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'link', 'Case studies')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
})
