/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim all service pages via main nav dropdowns', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opSeen(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation — spriteCloud')
  await opClick(page, 'link', 'Performance Testing')
  await opSeen(page, 'heading', 'Performance Testing — spriteCloud')
  await opClick(page, 'link', 'Cybersecurity & Penetration Testing')
  await opSeen(page, 'heading', 'Cybersecurity & Penetration Testing — spriteCloud')
})
