/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan events page for past or upcoming meetups', async ({ page }) => {
  await opGoto(page, '/events')
  await opSeen(page, 'link', 'QA Community Meetup April 2026')
})
