/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke From case study to contact with pre-filled interest', async ({ page }) => {
  await opGoto(page, '/case-study/postnl')
  await opClick(page, 'link', 'Contact us')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Test Automation')
  await opFill(page, 'Name', 'Maria')
  await opFill(page, 'Email', 'maria@company.com')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Thanks for contacting us!')
})
