/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage to career form submission (HR Internship)', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Careers')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opClick(page, 'button', 'Search')
})
