/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse all events from homepage menu', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Events & Meetups')
  await opSeen(page, 'link', 'Events & Meetups')
  await opSeen(page, 'link', 'QA Community Meetup April 2026')
})
