/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate from event page to unrelated case study', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL — Case Study — spriteCloud')
})
