/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Skim case study by name from homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
})
