/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check service filter on contact page', async ({ page }) => {
  await opGoto(page, '/contact')
  await opSeen(page, 'combobox', 'Which service are you interested in')
  await opSeen(page, 'link', 'Testing Services')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
})
