/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filter case studies by service relevance', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation case studies')
})
