/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan careers page for test automation roles', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'link', 'Test Automation Engineer')
})
