/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly verify functional testing page has no form', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opSeen(page, 'main', 'Functional Testing')
  await opSeen(page, 'button', 'Testing Services')
  await opSeen(page, 'button', 'Company')
})
