/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Check events page for upcoming meetups', async ({ page }) => {
  await opGoto(page, '/events')
  await opSeen(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'link', 'Summer QA Meetup August 2025')
  await opSeen(page, 'link', 'QA Meetup November 2025')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opSeen(page, 'heading', 'Barcelona IT Community Meetup May 2026')
})
