/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Switch between careers and events pages for engagement pathways', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'heading', 'QA Community Meetup April 2026')
})
