/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check careers page for engineering roles, then open two job pages', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opGoto(page, '/vacancy/hr-internship')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
})
