/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Double-click submit on contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'John Doe')
  await opFill(page, 'Email', 'john@example.com')
  await opFill(page, 'Message', 'Test message')
  await opClick(page, 'button', 'Send')
  await opClick(page, 'button', 'Send')
  await opSeen(page, 'main', 'Thank you. We will be in touch shortly.')
})
