/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate from event page to unrelated case study via navigation', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'link', 'Company')
  await opClick(page, 'link', 'About')
  await opClick(page, 'link', 'Contact')
  await opClick(page, 'link', 'Case Studies')
  await opClick(page, 'link', 'Oikocredit')
})
