/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage, jump directly to latest career entry via nav', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer — Careers — spriteCloud')
})
