/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quickly review multiple case studies using service context', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'GiftShift')
  await opSeen(page, 'link', 'Test Automation')
})
