/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discover career opportunities', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'button', 'Apply now')
  await opSeen(page, 'dialog', 'Application form')
})
