/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim homepage for company overview', async ({ page }) => {
  await opGoto(page, '/')
  await opSeen(page, 'banner', ' spriteCloud')
  await opClick(page, 'link', 'Company')
  await opSeen(page, 'heading', 'About spriteCloud')
})
