/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skimming event details via top menu', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Events')
  await opSeen(page, 'heading', 'Events & Meetups')
})
