/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim all testing service pages for feature summaries', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opSeen(page, 'heading', 'Test Automation')
  await opClick(page, 'link', 'Services')
  await opSeen(page, 'heading', 'Services')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Functional Testing')
  await opClick(page, 'link', 'Performance Testing')
  await opSeen(page, 'heading', 'Performance Testing')
})
