/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore case studies to assess real-world impact', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Case Study')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL')
})
