/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim case studies for automation coverage', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opSeen(page, 'link', 'Test Automation')
})
