/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit a contact inquiry for Test Automation', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'We\'re exploring automation for our CI/CD pipeline.')
  await opClick(page, 'button', 'Submit')
})
