/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Go directly to a specific case study and return to home', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'spriteCloud')
  await opSeen(page, 'main', 'QA & Software Testing Consultancy — spriteCloud')
})
