/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim career page headings for role types', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'heading', 'Careers')
  await opSeen(page, 'heading', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
})
