/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Simultaneous tab navigation on same page', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Testing Services — spriteCloud')
})
