/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim company values from about page', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About')
  await opSeen(page, 'heading', 'Our values')
})
