/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browser back navigation mid-career-application flow', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opClick(page, 'button', 'Apply Now')
  await opFill(page, 'Name', 'Jane Doe')
  await opPress(page, 'Backspace')
  await opGoto(page, '/careers')
  await opSeen(page, 'heading', 'Careers')
})
