/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Skim services overview page for core offerings', async ({ page }) => {
  await opGoto(page, '/services')
  await opSeen(page, 'heading', 'Testing Services')
  await opSeen(page, 'heading', 'Functional Testing')
  await opSeen(page, 'heading', 'Test Automation')
  await opSeen(page, 'heading', 'Performance Testing')
})
