/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Find a past event and view details', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'heading', 'QA Community Meetup April 2026')
})
