/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore service details and return to homepage', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'QA & Software Testing Consultancy — spriteCloud')
})
