/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Long-value spam in contact form', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'A very long name that is definitely not a real person but meant to test form validation with a name that stretches across the width of the screen many times over this is not a typo')
  await opFill(page, 'Email', 'x@x.x')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Message', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'main', 'Contact — spriteCloud')
})
