/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke From contact page, select service filter and submit inquiry', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opClick(page, 'button', 'Submit')
  await opSeen(page, 'heading', 'Thank you')
})
