/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Learn about Agentic Testing, a newer service offering', async ({ page }) => {
  await opGoto(page, '/agentic-testing')
  await opClick(page, 'link', 'Agentic Testing')
  await opClick(page, 'button', 'Talk to an expert')
  await opFill(page, 'Name', 'Jordan Smith')
  await opFill(page, 'Email', 'j.smith@company.com')
  await opSeen(page, 'heading', 'Thanks for reaching out — we’ll be in touch')
})
