/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-button loop after contact form fill', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Adversarial User')
  await opFill(page, 'Email', 'test@example.com')
  await opClick(page, 'button', 'Submit')
  await opPress(page, 'Back')
  await opSeen(page, 'heading', 'Contact')
})
