/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim case studies for ecommerce performance testing', async ({ page }) => {
  await opGoto(page, '/case-study/ecommerce-performance')
  await opSeen(page, 'heading', 'ECommerce platform')
  await opSeen(page, 'heading', 'Performance Testing case study')
  await opClick(page, 'link', 'Performance Testing')
  await opSeen(page, 'heading', 'Test Automation')
})
