/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke  browsing company values and culture', async ({ page }) => {
  await opGoto(page, '/about')
  await opSeen(page, 'heading', 'About')
  await opClick(page, 'link', 'Values')
  await opSeen(page, 'heading', 'Our Values')
  await opClick(page, 'link', 'How we work')
  await opSeen(page, 'heading', 'How We Work')
})
