/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim case study headings and services for relevance', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Oikocredit')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Functional Testing')
})
