/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Consider event participation by browsing upcoming meetups', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Events & Meetups')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opSeen(page, 'heading', 'Barcelona IT Community Meetup May 2026')
})
