/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Investigate a specific service in depth via the services hub', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'main', 'Test Automation — spriteCloud')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'main', 'Functional Testing — spriteCloud')
})
