/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse services from homepage to dedicated page', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'heading', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation')
})
