/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View a case study via case study listing page', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'heading', 'PostNL')
})
