/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate to services page then jump to event registration', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'Barcelona IT Community Meetup, May 2026')
  await opSeen(page, 'dialog', ' DIAG-formtrue-pastfalse-ctatrue')
})
