/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Check HR internship details without form interaction', async ({ page }) => {
  await opGoto(page, '/vacancy/hr-internship')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
  await opClick(page, 'link', 'Careers')
})
