/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discover upcoming events and RSVP', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register')
  await opFill(page, 'First name', 'Alex')
  await opFill(page, 'Last name', 'Rivera')
  await opFill(page, 'Email', 'alex.rivera@example.com')
  await opPress(page, 'Enter')
})
