/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Form fill → page refresh → verify persisted values', async ({ page }) => {
  await opGoto(page, '/events')
  await opFill(page, 'First Name', 'Alex')
  await opFill(page, 'Last Name', 'Smith')
  await opFill(page, 'Email', 'alex@smith.com')
  await opPress(page, 'F5')
  await opSeen(page, 'textbox', 'First Name')
  await opSeen(page, 'textbox', 'Last Name')
  await opSeen(page, 'textbox', 'Email')
})
