/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage, view a case study and instantly contact team', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Case Study — PostNL')
  await opClick(page, 'link', 'Contact')
  await opSeen(page, 'heading', 'Contact')
})
