/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigating via accordion menus to services without using top-level links', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'option', 'Functional Testing')
  await opPress(page, 'Tab')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'option', 'About')
  await opClick(page, 'link', 'Back to services')
  await opClick(page, 'link', 'Performance Testing')
})
