/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filter contact form by service and submit inquiry', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Test Automation')
  await opFill(page, 'Full name', 'Alex Chen')
  await opFill(page, 'Email', 'alex.chen@example.com')
  await opFill(page, 'Message', 'Our team needs help scaling CI/CD test pipelines.')
  await opPress(page, 'Enter')
})
