/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse events and check upcoming meetup registration flow', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register interest')
  await opSeen(page, 'dialog', 'Register interest')
})
