/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Compare two case studies side by side for performance testing proof', async ({ page }) => {
  await opGoto(page, '/case-study/postnl')
  await opSeen(page, 'heading', 'PostNL')
  await opGoto(page, '/case-study/ecommerce-performance')
  await opSeen(page, 'heading', 'eCommerce platform')
})
