/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Compare performance and automation service pages', async ({ page }) => {
  await opGoto(page, '/performance-testing')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Functionele Testing')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'heading', 'Oikocredit — Case Study — spriteCloud')
})
