/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-button flow after submitting case study form', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'Learn more about this case study')
  await opFill(page, 'Name', 'Back-Button Prober')
  await opFill(page, 'Email', 'back@prober.io')
  await opClick(page, 'button', 'Submit')
  await opPress(page, 'Backspace')
  await opClick(page, 'link', 'Back')
})
