/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapidly fill and submit form twice in same session', async ({ page }) => {
  await opGoto(page, '/events')
  await opFill(page, 'Name', 'RapidUser')
  await opFill(page, 'Email', 'rapid@example.com')
  await opPress(page, 'Enter')
  await opFill(page, 'Name', 'RapidUser')
  await opFill(page, 'Email', 'rapid2@example.com')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Thank You')
})
