/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Brows careers by scrolling to engineering openings', async ({ page }) => {
  await opGoto(page, '/careers')
  await opSeen(page, 'heading', 'Test Automation Engineer')
})
