/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke From homepage to functional testing deep-dive', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Functional Testing')
  await opSeen(page, 'heading', 'Functional Testing')
})
