/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Evaluate event participation and community engagement', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opSeen(page, 'heading', 'Barcelona IT Community Meetup May 2026')
  await opFill(page, 'Which service are you interested in?', 'Agentic Testing')
  await opClick(page, 'button', 'Register now')
})
