/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Quick overview of career positions by title', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'HR Internship')
  await opSeen(page, 'heading', 'HR Internship')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
})
