/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Opening two tabs and submitting contact from both', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your name', 'Tab One User')
  await opPress(page, 'Tab')
  await opFill(page, 'Your message', 'First tab submission attempt.')
  await opClick(page, 'button', 'Send message')
  await opGoto(page, '/contact')
  await opFill(page, 'Your name', 'Tab Two User')
  await opPress(page, 'Tab')
  await opFill(page, 'Your message', 'Second tab submission attempt.')
  await opClick(page, 'button', 'Send message')
  await opSeen(page, 'main', 'Contact -spriteCloud')
})
