/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Register for a future QA community meetup', async ({ page }) => {
  await opGoto(page, '/event/qa-community-meetup-april-2026')
  await opClick(page, 'button', 'Register Now')
  await opFill(page, 'First Name', 'Taylor')
  await opFill(page, 'Last Name', 'Kim')
  await opFill(page, 'Email', 'taylor.kim@example.com')
  await opClick(page, 'button', 'Register')
})
