/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke View corporate events calendar', async ({ page }) => {
  await opGoto(page, '/events')
  await opSeen(page, 'main', 'Events & Meetups')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'main', 'DIAG-formtrue-pastfalse-ctatrue')
})
