/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Back-button navigation from Careers to homepage mid-fill', async ({ page }) => {
  await opGoto(page, '/careers')
  await opFill(page, 'Your Name', 'James')
  await opFill(page, 'Email', 'james@company.com')
  await opClick(page, 'link', 'Back')
  await opSeen(page, 'main', 'QA & Software Testing Consultancy — spriteCloud')
})
