/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit contact form while rapidly pressing Enter', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Your Name', 'John Doe')
  await opFill(page, 'Your Email', 'johndoe@example.com')
  await opFill(page, 'Your Message', 'Hello')
  await opPress(page, 'Enter')
  await opPress(page, 'Enter')
  await opSeen(page, 'button', 'Send Message')
})
