/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Cross-tab navigation consistency during form fill', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'link', 'Functional Testing')
  await opFill(page, 'Name', 'Jane Smith')
  await opPress(page, 'Enter')
  await opSeen(page, 'main', 'Thank you for registering')
})
