/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate from首页 to past event page via events listing', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'link', 'Events & Meetups')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
})
