/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Refine contact request while exploring services page', async ({ page }) => {
  await opGoto(page, '/services')
  await opClick(page, 'link', 'Testing Services')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opClick(page, 'option', 'Test Automation')
  await opClick(page, 'link', 'contact us')
})
