/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Back-button mid-contact-form fill', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Your Name', 'John Smith')
  await opFill(page, 'Your Email', 'john@example.com')
  await opPress(page, 'BackSpace')
  await opClick(page, 'link', 'Contact')
  await opSeen(page, 'heading', 'Contact')
})
