/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim event page for dates and CTAs', async ({ page }) => {
  await opGoto(page, '/events')
  await opSeen(page, 'heading', 'Events & Meetups')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'heading', 'QA community meetup April 2026')
})
