/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate from homepage to careers to review open roles', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Company')
  await opClick(page, 'link', 'Careers')
  await opSeen(page, 'heading', 'Careers')
})
