/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Visitor browses events and fills contact form', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Your Name', 'Alex Johnson')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opClick(page, 'button', 'Send message')
})
