/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skimming all case study cards on Work page', async ({ page }) => {
  await opGoto(page, '/work')
  await opSeen(page, 'heading', 'Work')
  await opSeen(page, 'link', 'Oikocredit')
  await opSeen(page, 'link', 'PostNL')
  await opSeen(page, 'link', 'citizenM')
})
