/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Rapidly cycle through service pages via navigation link', async ({ page }) => {
  await opGoto(page, '/functional-testing')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Performance Testing')
  await opClick(page, 'link', 'Testing Services')
  await opSeen(page, 'heading', 'Testing Services')
})
