/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Discovering success stories via case studies', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'Oikocredit')
  await opSeen(page, 'main', 'Oikocredit — Case Study — spriteCloud')
  await opClick(page, 'link', 'PostNL')
  await opSeen(page, 'main', 'PostNL — Case Study — spriteCloud')
})
