/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Register for an upcoming QA community event', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opSeen(page, 'dialog', 'Event registration form')
})
