/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Contact support with Performance Testing query', async ({ page }) => {
  await opGoto(page, '/contact')
  await opClick(page, 'combobox', 'Which service are you interested in')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opPress(page, 'Enter')
  await opSeen(page, 'main', 'Contact')
})
