/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Browse company story via cases and press team', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Work')
  await opClick(page, 'link', 'Oikocredit')
  await opClick(page, 'link', 'SpriteCloud')
  await opSeen(page, 'heading', 'About')
})
