/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Visit homepage, review company info, and contact sales', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Company')
  await opClick(page, 'link', 'About')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opFill(page, 'Name', 'Alex Rivera')
  await opFill(page, 'Email', 'alex@example.com')
  await opClick(page, 'button', 'Send')
})
