/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Skim multiple events in one navigation pass', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opPress(page, 'BackSpace')
  await opPress(page, 'BackSpace')
  await opClick(page, 'link', 'spriteCloud')
  await opSeen(page, 'heading', 'Events & Meetups')
})
