/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Fill contact form with service filter using keyboard', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Functional Testing')
  await opPress(page, 'Tab')
  await opPress(page, 'Tab')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Contact')
})
