/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open contact form in two tabs and compare', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Alpha User')
  await opFill(page, 'Message', 'Tab A test')
  await opFill(page, 'Name', 'Beta User')
  await opFill(page, 'Message', 'Tab B test')
})
