/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Jump directly to a known case study from homepage', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'link', 'Case Study')
  await opSeen(page, 'main', 'Case Study')
})
