/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Quick review of past event pages', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA community meetup april 2026')
  await opSeen(page, 'heading', 'QA Community Meetup April 2026')
  await opClick(page, 'link', 'QA meetup march 2025')
  await opSeen(page, 'heading', 'QA Meetup March 2025')
})
