/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore a case study and contact for similar work', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opSeen(page, 'heading', 'Oikocredit')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opSeen(page, 'heading', 'Contact us')
})
