/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore a case study to validate expertise', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Case Study')
  await opClick(page, 'heading', 'Oikocredit')
  await opSeen(page, 'main', 'Oikocredit')
})
