/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filter contact form by specific service and submit', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'Alex')
  await opFill(page, 'Email', 'alex@example.com')
  await opFill(page, 'Message', 'Interested in your Test Automation services.')
  await opClick(page, 'button', 'Send')
})
