/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Register for an upcoming QA meetup', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Events')
  await opClick(page, 'link', 'Barcelona IT Community Meetup May 2026')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opClick(page, 'button', 'Register')
})
