/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Apply filter in contact form by service interest', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opFill(page, 'Name', 'John Doe')
  await opFill(page, 'Email', 'john@example.com')
  await opSeen(page, 'button', 'Send')
})
