/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim homepage headline and related testing services', async ({ page }) => {
  await opGoto(page, '/')
  await opSeen(page, 'heading', 'QA & Software Testing Consultancy')
  await opClick(page, 'link', 'Test Automation')
  await opSeen(page, 'heading', 'Test Automation')
})
