/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit empty event form then fill name only', async ({ page }) => {
  await opGoto(page, '/event/barcelona-it-community-meetup-may-2026')
  await opClick(page, 'button', 'Register')
  await opSeen(page, 'dialog', 'Please fill in all required fields')
  await opFill(page, 'Name', 'Alex')
  await opClick(page, 'button', 'Register')
  await opSeen(page, 'dialog', 'Registration confirmation')
})
