/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Skim homepage for company info and test automation link', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'heading', 'Company')
  await opSeen(page, 'link', 'About')
})
