/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Open contact page in two tabs and submit both', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'Jane Smith')
  await opFill(page, 'Email', 'jane@example.com')
  await opClick(page, 'button', 'Send message')
  await opSeen(page, 'dialog', 'Message sent successfully')
})
