/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore events and register for a meetup', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Events')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opSeen(page, 'main', 'QA community meetup April 2026')
  await opFill(page, 'Name', 'Alex Tester')
  await opFill(page, 'Email', 'alex@example.com')
  await opClick(page, 'button', 'Register')
})
