/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Scan case studies for tech/e-commerce domain example', async ({ page }) => {
  await opGoto(page, '/case-study/ecommerce-performance')
  await opSeen(page, 'heading', 'eCommerce platform')
})
