/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse open roles and learn about an Internship', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'HR Internship – Process & People')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
})
