/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filter contact form by specific service', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Which service are you interested in', 'Performance Testing')
  await opFill(page, 'Name', 'Jane Doe')
  await opFill(page, 'Email', 'jane@example.com')
  await opFill(page, 'Message', 'Interested in performance testing for our e-commerce platform')
  await opPress(page, 'Enter')
  await opSeen(page, 'heading', 'Thank you')
})
