/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Filter events by upcoming focus and register', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'tab', 'Upcoming')
  await opClick(page, 'link', 'QA Community Meetup April 2026')
  await opClick(page, 'button', 'Register now')
})
