/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore a case study and compare with similar work', async ({ page }) => {
  await opGoto(page, '/case-study/oikocredit')
  await opClick(page, 'link', 'PostNL')
  await opClick(page, 'link', 'Ben')
  await opClick(page, 'link', 'eCommerce platform')
  await opSeen(page, 'heading', 'eCommerce platform')
})
