/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Go to homepage, open careers form, open careers in new tab, refresh both', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Company')
  await opClick(page, 'link', 'Careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opFill(page, 'Email', 'test@example.com')
  await opPress(page, 'Tab')
  await opFill(page, 'Resume / CV', 'not-a-file')
  await opSeen(page, 'heading', 'Careers')
})
