/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Explore service details and contact for a quote', async ({ page }) => {
  await opGoto(page, '/test-automation')
  await opClick(page, 'link', 'Test Automation')
  await opClick(page, 'link', 'Contact')
  await opFill(page, 'Which service are you interested in', 'Test Automation')
  await opClick(page, 'button', 'Subscribe')
})
