/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Submit contact form with maximum-length inputs', async ({ page }) => {
  await opGoto(page, '/contact')
  await opFill(page, 'Name', 'A very long name that stretches across the page and tests input truncation without using special characters or symbols')
  await opFill(page, 'Email', 'extremelylongemailaddresswithlotsofcharactersandnumbers1234567890abcdefghijklmnopqrstuvwxyz@example.com')
  await opFill(page, 'Company', 'A very long company name that potentially exceeds database field limits and may trigger UI truncation or validation errors')
  await opPress(page, 'Tab')
  await opSeen(page, 'dialog', 'Error: Invalid email format')
})
