/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Browse event series by recurring meetups', async ({ page }) => {
  await opGoto(page, '/events')
  await opClick(page, 'link', 'QA Community Meetup')
  await opClick(page, 'link', 'Barcelona IT Community Meetup')
  await opClick(page, 'link', 'QA Meetup November 2025')
  await opSeen(page, 'heading', 'QA Meetup November 2025')
})
