/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Navigate to API docs and verify OpenAPI spec loads', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'petstore3.swagger.io')
  await opClick(page, 'link', 'Swagger UI')
  await opSeen(page, 'heading', 'Swagger UI')
})
