/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Open homepage in two tabs, interact in parallel', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Functional Testing')
  await opClick(page, 'menuitem', 'Testing Services')
  await opClick(page, 'link', 'Test Automation')
})
