/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:suite @smoke Evaluate team expertise via career openings', async ({ page }) => {
  await opGoto(page, '/careers')
  await opClick(page, 'link', 'Test Automation Engineer')
  await opSeen(page, 'heading', 'Test Automation Engineer')
  await opClick(page, 'link', 'HR Internship – Process & People')
  await opSeen(page, 'heading', 'HR Internship – Process & People')
})
