/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from './prims'

test('@journey:suite @smoke Read a case study about performance testing', async ({ page }) => {
  await opGoto(page, '/work')
  await opClick(page, 'link', 'eCommerce platform')
  await opSeen(page, 'heading', 'eCommerce platform')
})
