/** Generated by quail. */
import { test } from '@playwright/test'
import { opGoto, opClick, opFill, opPress, opSeen } from '../prims'

test('@journey:composed @smoke Create a new account', async ({ page }) => {
  await opGoto(page, '/')
  await opClick(page, 'link', 'Sign up')
  await opFill(page, 'Email', 'newuser@example.com')
  await opFill(page, 'Password', 'securePassword123')
  await opClick(page, 'checkbox', 'I agree to the Terms of Service')
  await opClick(page, 'button', 'Create account')
  await opSeen(page, 'alert', 'Account created successfully')
})
