/**
 * Generated by quail.
 *
 * Auth-expiry baseline for https://www.spritecloud.com/. Handles an expired session
 * gracefully — clearing storage mid-journey surfaces a sign-in
 * prompt or auth-expiry notice, not a blank screen or stack trace.
 *
 * Filter: `npx playwright test --grep @kind:auth-expiry`
 */
import { test, expect } from '@playwright/test'
import { mobileNav } from '../prims'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — auth expiry @ https://www.spritecloud.com/', () => {
  test('@kind:auth-expiry @smoke clearing cookies mid-journey surfaces a sign-in prompt', async ({ page, context }) => {
    await mobileNav(page, 'https://www.spritecloud.com/')
    await context.clearCookies()
    await page.evaluate(() => {
      try { localStorage.removeItem('token'); sessionStorage.clear() } catch {}
    })
    const internalLink = page.locator('a[href^="/"]:not([href^="//"])').first()
    if (await internalLink.count() === 0) test.skip()
    await internalLink.click({ timeout: 5000 }).catch(() => {})
    await page.waitForLoadState('domcontentloaded').catch(() => {})
    await expect(page.locator('h1, [role="heading"][aria-level="1"], form, [role="alert"]').first()).toBeVisible({ timeout: 10_000 })
    const body = await page.locator('body').innerText().catch(() => '')
    expect.soft(body.toLowerCase()).not.toContain('traceback')
    expect.soft(body.toLowerCase()).not.toContain('stack trace')
  })
})
