/**
 * Generated by quail.
 *
 * Accessibility landmark structure for https://www.spritecloud.com/agentic-testing. Five structural
 * checks the baseline axe scan does not enforce: single main/h1,
 * no focusables inside aria-hidden, heading hierarchy, duplicate
 * landmark names, skip-link.
 *
 * Filter: `npx playwright test --grep @kind:a11y-landmarks`
 */
import { test, expect } from '@playwright/test'
import { mobileNav } from '../prims'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — a11y landmarks @ https://www.spritecloud.com/agentic-testing', () => {
  test('@kind:a11y-landmarks @smoke single main + h1 + nav', async ({ page }) => {
    await mobileNav(page, 'https://www.spritecloud.com/agentic-testing')
    const mains = await page.locator('main, [role="main"]').count()
    expect.soft(mains, `expected exactly one <main> region`).toBe(1)
    const h1s = await page.locator('h1').count()
    expect.soft(h1s, `expected exactly one <h1>`).toBe(1)
    const navs = await page.locator('nav, [role="navigation"]').count()
    expect.soft(navs, `expected at least one <nav> region`).toBeGreaterThanOrEqual(1)
  })

  test('@kind:a11y-landmarks @negative no focusables inside aria-hidden', async ({ page }) => {
    await mobileNav(page, 'https://www.spritecloud.com/agentic-testing')
    const hiddenFocusables = await page.locator('[aria-hidden="true"]').locator('a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])').count()
    expect.soft(hiddenFocusables, `${hiddenFocusables} focusable elements inside aria-hidden — confusing for screen readers`).toBe(0)
  })

  test('@kind:a11y-landmarks @heading-hierarchy heading order is sequential', async ({ page }) => {
    await mobileNav(page, 'https://www.spritecloud.com/agentic-testing')
    const jumps = await page.evaluate(() => {
      const headings = Array.from(document.querySelectorAll('h1,h2,h3,h4,h5,h6'))
      const levels = headings.map((h) => parseInt(h.tagName.slice(1), 10))
      const issues: string[] = []
      let prev = 0
      for (let i = 0; i < levels.length; i++) {
        const cur = levels[i]
        if (prev > 0 && cur > prev + 1) {
          issues.push(`h${prev} → h${cur} skip at index ${i}: "${headings[i].textContent?.slice(0, 60) ?? ''}"`)
        }
        prev = cur
      }
      return issues
    })
    if (jumps.length > 0) console.log('heading hierarchy jumps:', jumps)
    expect.soft(jumps, `${jumps.length} heading-hierarchy jump(s)`).toEqual([])
  })

  test('@kind:a11y-landmarks @landmark-names duplicate landmarks have accessible names', async ({ page }) => {
    await mobileNav(page, 'https://www.spritecloud.com/agentic-testing')
    const unnamed = await page.evaluate(() => {
      const kinds = ['nav', 'aside', 'section']
      const issues: string[] = []
      for (const kind of kinds) {
        const els = Array.from(document.querySelectorAll(kind))
        if (els.length < 2) continue
        els.forEach((el, idx) => {
          const hasAriaLabel = !!el.getAttribute('aria-label')?.trim()
          const hasAriaLabelledBy = !!el.getAttribute('aria-labelledby')?.trim()
          const hasInnerHeading = !!el.querySelector('h1, h2, h3, h4, h5, h6')
          if (!hasAriaLabel && !hasAriaLabelledBy && !hasInnerHeading) {
            issues.push(`${kind}[${idx}] has no accessible name`)
          }
        })
      }
      return issues
    })
    if (unnamed.length > 0) console.log('unnamed-landmark issues:', unnamed)
    expect.soft(unnamed, `${unnamed.length} duplicate landmark(s) without an accessible name`).toEqual([])
  })

  test('@kind:a11y-landmarks @skip-link "skip to content" affordance present (WCAG 2.4.1)', async ({ page }) => {
    await mobileNav(page, 'https://www.spritecloud.com/agentic-testing')
    const hasSkipLink = await page.evaluate(() => {
      const candidates = Array.from(document.querySelectorAll('a[href^="#"]'))
      return candidates.some((a) => {
        const text = (a.textContent || '').toLowerCase()
        const href = a.getAttribute('href') || ''
        return /skip|jump|main content/.test(text) ||
               href === '#main' || href === '#content' ||
               !!document.querySelector(`${href}[role="main"], ${href}#main, main${href}`)
      })
    })
    expect.soft(hasSkipLink, 'no "skip to content" link found — WCAG 2.4.1 violation').toBe(true)
  })
})
