/**
 * Generated by quail.
 *
 * Browser-zoom baseline for https://www.spritecloud.com/performance-testing. WCAG 2.1 SC 1.4.4 requires pages
 * to remain functional at 200% zoom; we test 200% and 400% as a
 * stronger guarantee.
 *
 * Filter: `npx playwright test --grep @kind:zoom`
 */
import { test } from '@playwright/test'
import { mobileNav, assertHeadingVisible } from '../prims'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — zoom @ https://www.spritecloud.com/performance-testing', () => {
  for (const zoom of [2.0, 4.0] as const) {
    test(`@kind:zoom @smoke @zoom:${zoom * 100}% h1 stays visible`, async ({ page }) => {
      await mobileNav(page, 'https://www.spritecloud.com/performance-testing')
      await page.evaluate((z) => {
        const b = document.body
        if (b) {
          b.style.transformOrigin = '0 0'
          b.style.transform = `scale(${z})`
          b.style.width = `${100 / z}%`
        }
      }, zoom)
      await assertHeadingVisible(page)
    })
  }
})
