/**
 * Generated by quail.
 *
 * Accessibility-preferences baseline for https://www.spritecloud.com/test-automation. Asserts the page
 * respects UA preferences for reduced motion, forced colors, and
 * elevated contrast — mandated by WCAG 2.1 SC 2.3.3 and OS-level
 * user prefs.
 *
 * Filter: `npx playwright test --grep @kind:a11y-prefs`
 */
import { test, expect } from '@playwright/test'
import { withContext, mobileNav, assertHeadingVisible } from '../prims'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — a11y prefs @ https://www.spritecloud.com/test-automation', () => {
  test('@kind:a11y-prefs @reduced-motion renders with prefers-reduced-motion', async ({ browser }) => {
    await withContext(browser, { reducedMotion: 'reduce' }, async (page) => {
      await mobileNav(page, 'https://www.spritecloud.com/test-automation')
      await assertHeadingVisible(page)
      const sample = page.locator('[class*="anim"], [class*="transition"]').first()
      if (await sample.count() > 0) {
        const duration = await sample.evaluate((el) => getComputedStyle(el).animationDuration)
        expect.soft(duration === '0s' || duration === '' || duration.startsWith('0'), `expected reduced animation; got ${duration}`).toBeTruthy()
      }
    })
  })

  test('@kind:a11y-prefs @forced-colors renders under forced-colors', async ({ browser }) => {
    await withContext(browser, { forcedColors: 'active' }, async (page) => {
      await mobileNav(page, 'https://www.spritecloud.com/test-automation')
      await assertHeadingVisible(page)
    })
  })

  test('@kind:a11y-prefs @contrast renders with prefers-contrast: more', async ({ browser }) => {
    await withContext(browser, { contrast: 'more' }, async (page) => {
      await mobileNav(page, 'https://www.spritecloud.com/test-automation')
      await assertHeadingVisible(page)
    })
  })
})
