/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y @smoke no serious or critical axe violations
 *   - Spec:    tests/e2e/a11y/test-choice.a11y.spec.ts
 *   - Symptom: expected error triggered by broken accessibility logic
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Accessibility sentinel: medium severity, expected to fail until fix lands', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   expected error triggered by broken accessibility logic
  expect(`expected error triggered by broken accessibility logic`).toBe('') // bug present → string non-empty → fail
})
