/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:history-depth @smoke back twice then forward keeps the page interactive
 *   - Spec:    tests/e2e/history-depth/landing.history-depth.spec.ts
 *   - Symptom: TimeoutError occurred on page.goto (20s exceeded)
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('sentinel: history depth smoke test — back twice then forward keeps the page interactive (fails until bug fixed)', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   TimeoutError occurred on page.goto (20s exceeded)
  expect(`TimeoutError occurred on page.goto (20s exceeded)`).toBe('') // bug present → string non-empty → fail
})
