/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:visual @smoke page matches baseline (tablet)
 *   - Spec:    tests/e2e/visual/test-automation.visual.spec.ts
 *   - Symptom: TimeoutError: page.goto: Timeout 20000ms exceeded.
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('sentinel: visual regression test for tablet baseline (tablet) fails due to timeout', async ({ page }) => {
  // This sentinel mimics the original timeout failure. The test
  // remains marked `test.fail()` until the underlying bug is fixed.
  await page.goto('/')
  // Original symptom: page.goto() timed out after 20 seconds
  expect('TimeoutError: page.goto: Timeout 20000ms exceeded.').toBe('') // non-empty error string triggers expected failure
})
