/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y-landmarks @smoke single main + h1 + nav
 *   - Spec:    tests/e2e/a11y/contact.landmarks.spec.ts
 *   - Symptom: Error: expected exactly one <main> region
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('sentinel: accessibility — exactly one <main> region expected', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Reproduces the symptom: the page has no <main> or too many.
  expect('').toBe('Error: expected exactly one <main> region') // fails until bug is fixed
})
