/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:visual @smoke page matches baseline (tablet)
 *   - Spec:    tests/e2e/visual/landing.visual.spec.ts
 *   - Symptom: TimeoutError: page.goto: Timeout 20000ms exceeded.
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Bug sentinel: visual regression test times out on tablet load', async ({ page }) => {
  // This sentinel reproduces a timeout when loading the home page on tablet.
  // While the bug is unfixed, the test remains expected to fail.
  await page.goto('/')
  // Original symptom: page.goto hangs and times out after 20s on tablet view.
  expect(`TimeoutError: page.goto: Timeout 20000ms exceeded.`).toBe('') // bug present → string non-empty → fail
})
