/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y-landmarks @smoke single main + h1 + nav
 *   - Spec:    tests/e2e/a11y/case-study-ecomm-platform.landmarks.spec.ts
 *   - Symptom: Error: expected exactly one <main> region
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail(' sentinel: expects exactly one <main> region (a11y-landmarks smoke test)', async ({ page }) => {
  // Sentinel reproduces the original failing scenario:
  // Expected exactly one <main> HTML landmark region.
  await page.goto('/')
  // Symptom: expected exactly one <main> region
  expect('Error: expected exactly one <main> region').toBe('') // fail when bug is present
})
