/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:touch @smoke long-press on the primary CTA does not double-fire
 *   - Spec:    tests/e2e/touch/performance-testing.touch.spec.ts
 *   - Symptom: unexpected launch error occurred
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('bug-sentinel: long-press on primary CTA should not fire twice (E2E touch)', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   unexpected launch error occurred
  expect(`unexpected launch error occurred`).toBe('') // bug present → string non-empty → fail
})
