/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y @smoke no serious or critical axe violations
 *   - Spec:    tests/e2e/a11y/case-studies.a11y.spec.ts
 *   - Symptom: Error: expect(received).toHaveLength(expected)
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Sentinel test: accessibility smoke check — expect no serious or critical axe violations (currently failing)', async ({ page }) => {
  // This sentinel reproduces the original failing accessibility scenario.
  // It’s marked `test.fail()` so it reports expected failure while the bug exists,
  // and unexpectedly passes once the bug is fixed (indicating it’s time to graduate it).
  await page.goto('/')
  // Symptom from the ledger:
  //   Error: expect(received).toHaveLength(expected)
  expect('Error: expect(received).toHaveLength(expected)').toBe('') // fail while bug present
})
