/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     Accessibility: no serious or critical axe violations detected
 *   - Spec:    tests/e2e/a11y/case-studies.a11y.spec.ts
 *   - Symptom: Error: expect(received).toHaveLength(expected)
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('@kind:sentinel @severity:medium Accessibility: no serious or critical axe violations detected', async ({ page }) => {
  // This sentinel replicates the original accessibility failure.
  // The assertion is designed to fail while the bug persists;
  // passing means the bug is fixed — then remove this sentinel.
  await page.goto('/')
  // Symptom from the ledger:
  //   Error: expect(received).toHaveLength(expected)
  expect(`Error: expect(received).toHaveLength(expected)`).toBe('') // bug present → string non-empty → fail
})
