/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y-landmarks @smoke single main + h1 + nav
 *   - Spec:    tests/e2e/a11y/blog.landmarks.spec.ts
 *   - Symptom: Error: expected exactly one <main> region
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Sentinel: a11y landmarks — expected exactly one <main> region', async ({ page }) => {
  // Reproduces the original accessibility bug: should have exactly one <main> region.
  await page.goto('/')
  // Symptom from the ledger:
  //   Error: expected exactly one <main> region
  expect('').toBe('Error: expected exactly one <main> region') // bug present → assertion fails
})
