/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:responsive @smoke renders at tablet (768x1024)
 *   - Spec:    tests/e2e/responsive/contact.responsive.spec.ts
 *   - Symptom: TimeoutError: page.goto: Timeout 20000ms exceeded.
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Sentinel test: app times out on tablet (768x1024) — expect failure until bug is fixed', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   TimeoutError: page.goto: Timeout 20000ms exceeded.
  expect(`TimeoutError: page.goto: Timeout 20000ms exceeded.`).toBe('') // bug present → string non-empty → fail
})
