/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y-landmarks @smoke one main element, one h1, and at least one nav
 *   - Spec:    tests/e2e/a11y/test-automation.landmarks.spec.ts
 *   - Symptom: Expected exactly one <main> element
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('sentinel: a11y — page must contain exactly one <main>, one <h1>, and at least one <nav>', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   Expected exactly one <main> element
  expect(`Expected exactly one <main> element`).toBe('') // bug present → string non-empty → fail
})
