/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:race @smoke form survives a rapid double-submit
 *   - Spec:    tests/e2e/race/landing.race.spec.ts
 *   - Symptom: TimeoutError: page.goto: Timeout 20000ms exceeded.
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Sentinel test: form survives a rapid double-submit (race condition)'), async ({ page }) => {
  // This test reproduces the original failing scenario. quail
  // captures the symptom in the assertion; the test remains
  // marked `test.fail()` until the bug is fixed.
  await page.goto('/')
  // Symptom from the ledger:
  //   TimeoutError: page.goto: Timeout 20000ms exceeded.
  expect(`TimeoutError: page.goto: Timeout 20000ms exceeded.`).toBe('') // Fails while bug is present (non-empty string)
})
