/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     Accessibility: no serious or critical axe violations on homepage
 *   - Spec:    tests/e2e/a11y/case-study-ecomm-platform.a11y.spec.ts
 *   - Symptom: Accessibility audit failed: unexpected DOM length mismatch
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('@kind:sentinel @severity:medium Accessibility: no serious or critical axe violations on homepage', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   Accessibility audit failed: unexpected DOM length mismatch
  expect(`Accessibility audit failed: unexpected DOM length mismatch`).toBe('') // bug present → string non-empty → fail
})
