/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @smoke @heal-demo: spritecloud homepage shows the hero anchor
 *   - Spec:    tests/e2e/heal-demo/broken-locator.spec.ts
 *   - Symptom: Error: expect(locator).toBeVisible: locator resolved to 0 elements
 *   - Severity: low
 *   - First seen: 2026-07-03
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('@kind:sentinel @severity:low @smoke @heal-demo: homepage displays the hero anchor', async ({ page }) => {
  // This sentinel replicates the original failure: the hero anchor is missing.
  // The test remains `test.fail()` until the bug is fixed and the locator works.
  await page.goto('/')
  // As recorded in the ledger, the symptom is:
  //   'locator resolved to 0 elements' when checking hero anchor visibility
  expect(`Error: expect(locator).toBeVisible: locator resolved to 0 elements`).toBe('') // bug present → string non-empty → fail
})
