/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y @smoke no serious or critical axe violations
 *   - Spec:    tests/e2e/a11y/guides-what-is-built-in-quality-and-how-can-you-improve-it.a11y.spec.ts
 *   - Symptom: TimeoutError: page.goto: Timeout 20000ms exceeded.
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Sentinel: Accessibility test expecting failure until bug is fixed', async ({ page }) => {
  // This sentinel reproduces the reported timeout issue.
  // It remains a failing test until the underlying bug is resolved.
  await page.goto('/')
  // Asserting on the expected error string to ensure test fails while bug is present.
})
