/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     a single <main> element with <h1> and <nav> landmarks is present
 *   - Spec:    tests/e2e/a11y/guides-detox-guide.landmarks.spec.ts
 *   - Symptom: Exactly one <main> element should be present
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('@kind:sentinel @severity:medium a single <main> element with <h1> and <nav> landmarks is present', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   Exactly one <main> element should be present
  expect(`Exactly one <main> element should be present`).toBe('') // bug present → string non-empty → fail
})
