/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:responsive @smoke renders at tablet (768x1024)
 *   - Spec:    tests/e2e/responsive/cybersecurity.responsive.spec.ts
 *   - Symptom: Timed out waiting for page to load (20s exceeded)
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('@kind:sentinel @severity:medium @kind:responsive @smoke renders at tablet (768x1024)', async ({ page }) => {
  // The sentinel reproduces the original failing scenario. quail
  // bottles the symptom into the assertion below; the test stays
  // marked `test.fail()` until the bug is resolved.
  await page.goto('/')
  // Symptom from the ledger:
  //   Timed out waiting for page to load (20s exceeded)
  expect(`Timed out waiting for page to load (20s exceeded)`).toBe('') // bug present → string non-empty → fail
})
