/**
 * Generated by quail from the bug-discovery ledger.
 *
 * Bug SENTINEL — this spec is intentionally `test.fail()`. It will
 * report "expected to fail" while the underlying bug stays unfixed,
 * and pivot to "unexpected pass" the moment the fix lands. That
 * pivot is your signal to remove the sentinel and graduate it to
 * a regular regression test.
 *
 *   - Bug:     @kind:a11y-landmarks @smoke single main + h1 + nav
 *   - Spec:    tests/e2e/a11y/guides.landmarks.spec.ts
 *   - Symptom: Error: expected exactly one <main> region
 *   - Severity: medium
 *   - First seen: 2026-06-20
 *
 * Filter: `npx playwright test --grep @kind:sentinel`
 */
import { test, expect } from '@playwright/test'

test.fail('Sentinel: verifies single <main> region exists when h1 and nav are present', async ({ page }) => {
  // Reproduces original issue: page lacks exactly one <main> region despite presence of h1 and nav
  await page.goto('/')
  // Symptom from the ledger:
  //   Error: expected exactly one <main> region
  expect(`Error: expected exactly one <main> region`).toBe('')
})
