/**
 * Generated by quail.
 *
 * Print-stylesheet baseline for https://www.spritecloud.com/. Asserts the page renders
 * cleanly under media: 'print' — content visible, no overlapping
 * fixed elements.
 *
 * Filter: `npx playwright test --grep @kind:print`
 */
import { test, expect } from '@playwright/test'
import { mobileNav } from '../prims'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — print @ https://www.spritecloud.com/', () => {
  test('@kind:print @smoke renders under media: print', async ({ page }) => {
    await mobileNav(page, 'https://www.spritecloud.com/')
    await page.emulateMedia({ media: 'print' })
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeAttached()
    const fixedBanners = page.locator('[class*="cookie"], [class*="banner"]').filter({ visible: true })
    const cnt = await fixedBanners.count()
    expect.soft(cnt, `${cnt} fixed banners still visible under print media — likely missing @media print { display: none } rule`).toBeLessThanOrEqual(1)
  })
})
