/**
 * Generated by quail.
 *
 * Mobile-web smoke for https://www.spritecloud.com/performance-testing. Iterates a deterministic device matrix
 * (iPhone 13 / Pixel 5 / iPad Pro 11 / Galaxy S9+) and runs a smoke
 * plus an orientation flip on each — 8 tests per page.
 *
 * Filter: `npx playwright test --grep @kind:mobile`
 */
import { test } from '@playwright/test'
import {
  DEVICE_MATRIX,
  withDevice,
  withDeviceRotated,
  mobileNav,
  assertHeadingVisible,
  tapPrimaryCTA,
} from '../prims'

test.describe.configure({ mode: 'parallel' })

for (const deviceName of DEVICE_MATRIX) {
  test(`@kind:mobile @smoke @device:${deviceName} viewport renders without breakage`, async ({ browser }) => {
    await withDevice(browser, deviceName, async (page) => {
      await mobileNav(page, 'https://www.spritecloud.com/performance-testing')
      await assertHeadingVisible(page)
      await tapPrimaryCTA(page)
    })
  })

  test(`@kind:mobile @orientation @device:${deviceName} landscape rotation keeps the page interactive`, async ({ browser }) => {
    const result = await withDeviceRotated(browser, deviceName, async (page) => {
      await mobileNav(page, 'https://www.spritecloud.com/performance-testing')
      await assertHeadingVisible(page)
    })
    if (result === 'skipped') test.skip()
  })
}
